//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AX_CRT_Mage_Connector.Navision_CustomerListService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/page/customerlist", ConfigurationName="Navision_CustomerListService.CustomerList_Port")]
    public interface CustomerList_Port {
        
        // CODEGEN: Generating message contract since the wrapper name (Read_Result) of message Read_Result does not match the default value (Read)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/customerlist:Read", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AX_CRT_Mage_Connector.Navision_CustomerListService.Read_Result Read(AX_CRT_Mage_Connector.Navision_CustomerListService.Read request);
        
        // CODEGEN: Generating message contract since the wrapper name (ReadByRecId_Result) of message ReadByRecId_Result does not match the default value (ReadByRecId)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/customerlist:ReadByRecId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AX_CRT_Mage_Connector.Navision_CustomerListService.ReadByRecId_Result ReadByRecId(AX_CRT_Mage_Connector.Navision_CustomerListService.ReadByRecId request);
        
        // CODEGEN: Generating message contract since the wrapper name (ReadMultiple_Result) of message ReadMultiple_Result does not match the default value (ReadMultiple)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/customerlist:ReadMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AX_CRT_Mage_Connector.Navision_CustomerListService.ReadMultiple_Result ReadMultiple(AX_CRT_Mage_Connector.Navision_CustomerListService.ReadMultiple request);
        
        // CODEGEN: Generating message contract since the wrapper name (IsUpdated_Result) of message IsUpdated_Result does not match the default value (IsUpdated)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/customerlist:IsUpdated", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AX_CRT_Mage_Connector.Navision_CustomerListService.IsUpdated_Result IsUpdated(AX_CRT_Mage_Connector.Navision_CustomerListService.IsUpdated request);
        
        // CODEGEN: Generating message contract since the wrapper name (GetRecIdFromKey_Result) of message GetRecIdFromKey_Result does not match the default value (GetRecIdFromKey)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/customerlist:GetRecIdFromKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AX_CRT_Mage_Connector.Navision_CustomerListService.GetRecIdFromKey_Result GetRecIdFromKey(AX_CRT_Mage_Connector.Navision_CustomerListService.GetRecIdFromKey request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/customerlist")]
    public partial class CustomerList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string noField;
        
        private string nameField;
        
        private string differentiatorField;
        
        private string addressField;
        
        private string address_2Field;
        
        private string state_CodeField;
        
        private string salesperson_CodeField;
        
        private string search_NameField;
        
        private string address_3Field;
        
        private string e_MailField;
        
        private string t_I_N_NoField;
        
        private Blocked blockedField;
        
        private bool blockedFieldSpecified;
        
        private bool prices_Including_VATField;
        
        private bool prices_Including_VATFieldSpecified;
        
        private decimal balanceField;
        
        private bool balanceFieldSpecified;
        
        private decimal balance_LCYField;
        
        private bool balance_LCYFieldSpecified;
        
        private Cust_Type cust_TypeField;
        
        private bool cust_TypeFieldSpecified;
        
        private decimal net_ChangeField;
        
        private bool net_ChangeFieldSpecified;
        
        private decimal net_Change_LCYField;
        
        private bool net_Change_LCYFieldSpecified;
        
        private string global_Dimension_1_CodeField;
        
        private string responsibility_CenterField;
        
        private string location_CodeField;
        
        private string countyField;
        
        private string post_CodeField;
        
        private string country_Region_CodeField;
        
        private string phone_NoField;
        
        private string fax_NoField;
        
        private string iC_Partner_CodeField;
        
        private string contactField;
        
        private string customer_Posting_GroupField;
        
        private string gen_Bus_Posting_GroupField;
        
        private string vAT_Bus_Posting_GroupField;
        
        private string customer_Price_GroupField;
        
        private string customer_Disc_GroupField;
        
        private string payment_Terms_CodeField;
        
        private string reminder_Terms_CodeField;
        
        private string fin_Charge_Terms_CodeField;
        
        private string currency_CodeField;
        
        private string language_CodeField;
        
        private decimal credit_Limit_LCYField;
        
        private bool credit_Limit_LCYFieldSpecified;
        
        private System.DateTime last_Date_ModifiedField;
        
        private bool last_Date_ModifiedFieldSpecified;
        
        private Application_Method application_MethodField;
        
        private bool application_MethodFieldSpecified;
        
        private bool combine_ShipmentsField;
        
        private bool combine_ShipmentsFieldSpecified;
        
        private Reserve reserveField;
        
        private bool reserveFieldSpecified;
        
        private Shipping_Advice shipping_AdviceField;
        
        private bool shipping_AdviceFieldSpecified;
        
        private string shipping_Agent_CodeField;
        
        private string base_Calendar_CodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
                this.RaisePropertyChanged("No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Differentiator {
            get {
                return this.differentiatorField;
            }
            set {
                this.differentiatorField = value;
                this.RaisePropertyChanged("Differentiator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Address_2 {
            get {
                return this.address_2Field;
            }
            set {
                this.address_2Field = value;
                this.RaisePropertyChanged("Address_2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string State_Code {
            get {
                return this.state_CodeField;
            }
            set {
                this.state_CodeField = value;
                this.RaisePropertyChanged("State_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Salesperson_Code {
            get {
                return this.salesperson_CodeField;
            }
            set {
                this.salesperson_CodeField = value;
                this.RaisePropertyChanged("Salesperson_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Search_Name {
            get {
                return this.search_NameField;
            }
            set {
                this.search_NameField = value;
                this.RaisePropertyChanged("Search_Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Address_3 {
            get {
                return this.address_3Field;
            }
            set {
                this.address_3Field = value;
                this.RaisePropertyChanged("Address_3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string E_Mail {
            get {
                return this.e_MailField;
            }
            set {
                this.e_MailField = value;
                this.RaisePropertyChanged("E_Mail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string T_I_N_No {
            get {
                return this.t_I_N_NoField;
            }
            set {
                this.t_I_N_NoField = value;
                this.RaisePropertyChanged("T_I_N_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public Blocked Blocked {
            get {
                return this.blockedField;
            }
            set {
                this.blockedField = value;
                this.RaisePropertyChanged("Blocked");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BlockedSpecified {
            get {
                return this.blockedFieldSpecified;
            }
            set {
                this.blockedFieldSpecified = value;
                this.RaisePropertyChanged("BlockedSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public bool Prices_Including_VAT {
            get {
                return this.prices_Including_VATField;
            }
            set {
                this.prices_Including_VATField = value;
                this.RaisePropertyChanged("Prices_Including_VAT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Prices_Including_VATSpecified {
            get {
                return this.prices_Including_VATFieldSpecified;
            }
            set {
                this.prices_Including_VATFieldSpecified = value;
                this.RaisePropertyChanged("Prices_Including_VATSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public decimal Balance {
            get {
                return this.balanceField;
            }
            set {
                this.balanceField = value;
                this.RaisePropertyChanged("Balance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BalanceSpecified {
            get {
                return this.balanceFieldSpecified;
            }
            set {
                this.balanceFieldSpecified = value;
                this.RaisePropertyChanged("BalanceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public decimal Balance_LCY {
            get {
                return this.balance_LCYField;
            }
            set {
                this.balance_LCYField = value;
                this.RaisePropertyChanged("Balance_LCY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Balance_LCYSpecified {
            get {
                return this.balance_LCYFieldSpecified;
            }
            set {
                this.balance_LCYFieldSpecified = value;
                this.RaisePropertyChanged("Balance_LCYSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public Cust_Type Cust_Type {
            get {
                return this.cust_TypeField;
            }
            set {
                this.cust_TypeField = value;
                this.RaisePropertyChanged("Cust_Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Cust_TypeSpecified {
            get {
                return this.cust_TypeFieldSpecified;
            }
            set {
                this.cust_TypeFieldSpecified = value;
                this.RaisePropertyChanged("Cust_TypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public decimal Net_Change {
            get {
                return this.net_ChangeField;
            }
            set {
                this.net_ChangeField = value;
                this.RaisePropertyChanged("Net_Change");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Net_ChangeSpecified {
            get {
                return this.net_ChangeFieldSpecified;
            }
            set {
                this.net_ChangeFieldSpecified = value;
                this.RaisePropertyChanged("Net_ChangeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public decimal Net_Change_LCY {
            get {
                return this.net_Change_LCYField;
            }
            set {
                this.net_Change_LCYField = value;
                this.RaisePropertyChanged("Net_Change_LCY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Net_Change_LCYSpecified {
            get {
                return this.net_Change_LCYFieldSpecified;
            }
            set {
                this.net_Change_LCYFieldSpecified = value;
                this.RaisePropertyChanged("Net_Change_LCYSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string Global_Dimension_1_Code {
            get {
                return this.global_Dimension_1_CodeField;
            }
            set {
                this.global_Dimension_1_CodeField = value;
                this.RaisePropertyChanged("Global_Dimension_1_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string Responsibility_Center {
            get {
                return this.responsibility_CenterField;
            }
            set {
                this.responsibility_CenterField = value;
                this.RaisePropertyChanged("Responsibility_Center");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string Location_Code {
            get {
                return this.location_CodeField;
            }
            set {
                this.location_CodeField = value;
                this.RaisePropertyChanged("Location_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string County {
            get {
                return this.countyField;
            }
            set {
                this.countyField = value;
                this.RaisePropertyChanged("County");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string Post_Code {
            get {
                return this.post_CodeField;
            }
            set {
                this.post_CodeField = value;
                this.RaisePropertyChanged("Post_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string Country_Region_Code {
            get {
                return this.country_Region_CodeField;
            }
            set {
                this.country_Region_CodeField = value;
                this.RaisePropertyChanged("Country_Region_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string Phone_No {
            get {
                return this.phone_NoField;
            }
            set {
                this.phone_NoField = value;
                this.RaisePropertyChanged("Phone_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string Fax_No {
            get {
                return this.fax_NoField;
            }
            set {
                this.fax_NoField = value;
                this.RaisePropertyChanged("Fax_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string IC_Partner_Code {
            get {
                return this.iC_Partner_CodeField;
            }
            set {
                this.iC_Partner_CodeField = value;
                this.RaisePropertyChanged("IC_Partner_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string Contact {
            get {
                return this.contactField;
            }
            set {
                this.contactField = value;
                this.RaisePropertyChanged("Contact");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string Customer_Posting_Group {
            get {
                return this.customer_Posting_GroupField;
            }
            set {
                this.customer_Posting_GroupField = value;
                this.RaisePropertyChanged("Customer_Posting_Group");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string Gen_Bus_Posting_Group {
            get {
                return this.gen_Bus_Posting_GroupField;
            }
            set {
                this.gen_Bus_Posting_GroupField = value;
                this.RaisePropertyChanged("Gen_Bus_Posting_Group");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string VAT_Bus_Posting_Group {
            get {
                return this.vAT_Bus_Posting_GroupField;
            }
            set {
                this.vAT_Bus_Posting_GroupField = value;
                this.RaisePropertyChanged("VAT_Bus_Posting_Group");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string Customer_Price_Group {
            get {
                return this.customer_Price_GroupField;
            }
            set {
                this.customer_Price_GroupField = value;
                this.RaisePropertyChanged("Customer_Price_Group");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string Customer_Disc_Group {
            get {
                return this.customer_Disc_GroupField;
            }
            set {
                this.customer_Disc_GroupField = value;
                this.RaisePropertyChanged("Customer_Disc_Group");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public string Payment_Terms_Code {
            get {
                return this.payment_Terms_CodeField;
            }
            set {
                this.payment_Terms_CodeField = value;
                this.RaisePropertyChanged("Payment_Terms_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public string Reminder_Terms_Code {
            get {
                return this.reminder_Terms_CodeField;
            }
            set {
                this.reminder_Terms_CodeField = value;
                this.RaisePropertyChanged("Reminder_Terms_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public string Fin_Charge_Terms_Code {
            get {
                return this.fin_Charge_Terms_CodeField;
            }
            set {
                this.fin_Charge_Terms_CodeField = value;
                this.RaisePropertyChanged("Fin_Charge_Terms_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public string Currency_Code {
            get {
                return this.currency_CodeField;
            }
            set {
                this.currency_CodeField = value;
                this.RaisePropertyChanged("Currency_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public string Language_Code {
            get {
                return this.language_CodeField;
            }
            set {
                this.language_CodeField = value;
                this.RaisePropertyChanged("Language_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        public decimal Credit_Limit_LCY {
            get {
                return this.credit_Limit_LCYField;
            }
            set {
                this.credit_Limit_LCYField = value;
                this.RaisePropertyChanged("Credit_Limit_LCY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Credit_Limit_LCYSpecified {
            get {
                return this.credit_Limit_LCYFieldSpecified;
            }
            set {
                this.credit_Limit_LCYFieldSpecified = value;
                this.RaisePropertyChanged("Credit_Limit_LCYSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=40)]
        public System.DateTime Last_Date_Modified {
            get {
                return this.last_Date_ModifiedField;
            }
            set {
                this.last_Date_ModifiedField = value;
                this.RaisePropertyChanged("Last_Date_Modified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Last_Date_ModifiedSpecified {
            get {
                return this.last_Date_ModifiedFieldSpecified;
            }
            set {
                this.last_Date_ModifiedFieldSpecified = value;
                this.RaisePropertyChanged("Last_Date_ModifiedSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=41)]
        public Application_Method Application_Method {
            get {
                return this.application_MethodField;
            }
            set {
                this.application_MethodField = value;
                this.RaisePropertyChanged("Application_Method");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Application_MethodSpecified {
            get {
                return this.application_MethodFieldSpecified;
            }
            set {
                this.application_MethodFieldSpecified = value;
                this.RaisePropertyChanged("Application_MethodSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=42)]
        public bool Combine_Shipments {
            get {
                return this.combine_ShipmentsField;
            }
            set {
                this.combine_ShipmentsField = value;
                this.RaisePropertyChanged("Combine_Shipments");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Combine_ShipmentsSpecified {
            get {
                return this.combine_ShipmentsFieldSpecified;
            }
            set {
                this.combine_ShipmentsFieldSpecified = value;
                this.RaisePropertyChanged("Combine_ShipmentsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=43)]
        public Reserve Reserve {
            get {
                return this.reserveField;
            }
            set {
                this.reserveField = value;
                this.RaisePropertyChanged("Reserve");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReserveSpecified {
            get {
                return this.reserveFieldSpecified;
            }
            set {
                this.reserveFieldSpecified = value;
                this.RaisePropertyChanged("ReserveSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=44)]
        public Shipping_Advice Shipping_Advice {
            get {
                return this.shipping_AdviceField;
            }
            set {
                this.shipping_AdviceField = value;
                this.RaisePropertyChanged("Shipping_Advice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Shipping_AdviceSpecified {
            get {
                return this.shipping_AdviceFieldSpecified;
            }
            set {
                this.shipping_AdviceFieldSpecified = value;
                this.RaisePropertyChanged("Shipping_AdviceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=45)]
        public string Shipping_Agent_Code {
            get {
                return this.shipping_Agent_CodeField;
            }
            set {
                this.shipping_Agent_CodeField = value;
                this.RaisePropertyChanged("Shipping_Agent_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=46)]
        public string Base_Calendar_Code {
            get {
                return this.base_Calendar_CodeField;
            }
            set {
                this.base_Calendar_CodeField = value;
                this.RaisePropertyChanged("Base_Calendar_Code");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/customerlist")]
    public enum Blocked {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        Ship,
        
        /// <remarks/>
        Invoice,
        
        /// <remarks/>
        All,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/customerlist")]
    public enum Cust_Type {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        Dealer,
        
        /// <remarks/>
        Sub_Dealer,
        
        /// <remarks/>
        End_User,
        
        /// <remarks/>
        Govt,
        
        /// <remarks/>
        Distributor,
        
        /// <remarks/>
        T_I_N_Applied,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/customerlist")]
    public enum Application_Method {
        
        /// <remarks/>
        Manual,
        
        /// <remarks/>
        Apply_to_Oldest,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/customerlist")]
    public enum Reserve {
        
        /// <remarks/>
        Never,
        
        /// <remarks/>
        Optional,
        
        /// <remarks/>
        Always,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/customerlist")]
    public enum Shipping_Advice {
        
        /// <remarks/>
        Partial,
        
        /// <remarks/>
        Complete,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/customerlist")]
    public partial class CustomerList_Filter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CustomerList_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CustomerList_Fields Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
                this.RaisePropertyChanged("Field");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
                this.RaisePropertyChanged("Criteria");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/customerlist")]
    public enum CustomerList_Fields {
        
        /// <remarks/>
        No,
        
        /// <remarks/>
        Name,
        
        /// <remarks/>
        Differentiator,
        
        /// <remarks/>
        Address,
        
        /// <remarks/>
        Address_2,
        
        /// <remarks/>
        State_Code,
        
        /// <remarks/>
        Salesperson_Code,
        
        /// <remarks/>
        Search_Name,
        
        /// <remarks/>
        Address_3,
        
        /// <remarks/>
        E_Mail,
        
        /// <remarks/>
        T_I_N_No,
        
        /// <remarks/>
        Blocked,
        
        /// <remarks/>
        Prices_Including_VAT,
        
        /// <remarks/>
        Balance,
        
        /// <remarks/>
        Balance_LCY,
        
        /// <remarks/>
        Cust_Type,
        
        /// <remarks/>
        Net_Change,
        
        /// <remarks/>
        Net_Change_LCY,
        
        /// <remarks/>
        Global_Dimension_1_Code,
        
        /// <remarks/>
        Responsibility_Center,
        
        /// <remarks/>
        Location_Code,
        
        /// <remarks/>
        County,
        
        /// <remarks/>
        Post_Code,
        
        /// <remarks/>
        Country_Region_Code,
        
        /// <remarks/>
        Phone_No,
        
        /// <remarks/>
        Fax_No,
        
        /// <remarks/>
        IC_Partner_Code,
        
        /// <remarks/>
        Contact,
        
        /// <remarks/>
        Customer_Posting_Group,
        
        /// <remarks/>
        Gen_Bus_Posting_Group,
        
        /// <remarks/>
        VAT_Bus_Posting_Group,
        
        /// <remarks/>
        Customer_Price_Group,
        
        /// <remarks/>
        Customer_Disc_Group,
        
        /// <remarks/>
        Payment_Terms_Code,
        
        /// <remarks/>
        Reminder_Terms_Code,
        
        /// <remarks/>
        Fin_Charge_Terms_Code,
        
        /// <remarks/>
        Currency_Code,
        
        /// <remarks/>
        Language_Code,
        
        /// <remarks/>
        Credit_Limit_LCY,
        
        /// <remarks/>
        Last_Date_Modified,
        
        /// <remarks/>
        Application_Method,
        
        /// <remarks/>
        Combine_Shipments,
        
        /// <remarks/>
        Reserve,
        
        /// <remarks/>
        Shipping_Advice,
        
        /// <remarks/>
        Shipping_Agent_Code,
        
        /// <remarks/>
        Base_Calendar_Code,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read", WrapperNamespace="urn:microsoft-dynamics-schemas/page/customerlist", IsWrapped=true)]
    public partial class Read {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/customerlist", Order=0)]
        public string No;
        
        public Read() {
        }
        
        public Read(string No) {
            this.No = No;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/customerlist", IsWrapped=true)]
    public partial class Read_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/customerlist", Order=0)]
        public AX_CRT_Mage_Connector.Navision_CustomerListService.CustomerList CustomerList;
        
        public Read_Result() {
        }
        
        public Read_Result(AX_CRT_Mage_Connector.Navision_CustomerListService.CustomerList CustomerList) {
            this.CustomerList = CustomerList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId", WrapperNamespace="urn:microsoft-dynamics-schemas/page/customerlist", IsWrapped=true)]
    public partial class ReadByRecId {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/customerlist", Order=0)]
        public string recId;
        
        public ReadByRecId() {
        }
        
        public ReadByRecId(string recId) {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/customerlist", IsWrapped=true)]
    public partial class ReadByRecId_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/customerlist", Order=0)]
        public AX_CRT_Mage_Connector.Navision_CustomerListService.CustomerList CustomerList;
        
        public ReadByRecId_Result() {
        }
        
        public ReadByRecId_Result(AX_CRT_Mage_Connector.Navision_CustomerListService.CustomerList CustomerList) {
            this.CustomerList = CustomerList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/customerlist", IsWrapped=true)]
    public partial class ReadMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/customerlist", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("filter")]
        public AX_CRT_Mage_Connector.Navision_CustomerListService.CustomerList_Filter[] filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/customerlist", Order=1)]
        public string bookmarkKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/customerlist", Order=2)]
        public int setSize;
        
        public ReadMultiple() {
        }
        
        public ReadMultiple(AX_CRT_Mage_Connector.Navision_CustomerListService.CustomerList_Filter[] filter, string bookmarkKey, int setSize) {
            this.filter = filter;
            this.bookmarkKey = bookmarkKey;
            this.setSize = setSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/customerlist", IsWrapped=true)]
    public partial class ReadMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadMultiple_Result", Namespace="urn:microsoft-dynamics-schemas/page/customerlist", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public AX_CRT_Mage_Connector.Navision_CustomerListService.CustomerList[] ReadMultiple_Result1;
        
        public ReadMultiple_Result() {
        }
        
        public ReadMultiple_Result(AX_CRT_Mage_Connector.Navision_CustomerListService.CustomerList[] ReadMultiple_Result1) {
            this.ReadMultiple_Result1 = ReadMultiple_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated", WrapperNamespace="urn:microsoft-dynamics-schemas/page/customerlist", IsWrapped=true)]
    public partial class IsUpdated {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/customerlist", Order=0)]
        public string Key;
        
        public IsUpdated() {
        }
        
        public IsUpdated(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/customerlist", IsWrapped=true)]
    public partial class IsUpdated_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUpdated_Result", Namespace="urn:microsoft-dynamics-schemas/page/customerlist", Order=0)]
        public bool IsUpdated_Result1;
        
        public IsUpdated_Result() {
        }
        
        public IsUpdated_Result(bool IsUpdated_Result1) {
            this.IsUpdated_Result1 = IsUpdated_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey", WrapperNamespace="urn:microsoft-dynamics-schemas/page/customerlist", IsWrapped=true)]
    public partial class GetRecIdFromKey {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/customerlist", Order=0)]
        public string Key;
        
        public GetRecIdFromKey() {
        }
        
        public GetRecIdFromKey(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/customerlist", IsWrapped=true)]
    public partial class GetRecIdFromKey_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecIdFromKey_Result", Namespace="urn:microsoft-dynamics-schemas/page/customerlist", Order=0)]
        public string GetRecIdFromKey_Result1;
        
        public GetRecIdFromKey_Result() {
        }
        
        public GetRecIdFromKey_Result(string GetRecIdFromKey_Result1) {
            this.GetRecIdFromKey_Result1 = GetRecIdFromKey_Result1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CustomerList_PortChannel : AX_CRT_Mage_Connector.Navision_CustomerListService.CustomerList_Port, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerList_PortClient : System.ServiceModel.ClientBase<AX_CRT_Mage_Connector.Navision_CustomerListService.CustomerList_Port>, AX_CRT_Mage_Connector.Navision_CustomerListService.CustomerList_Port {
        
        public CustomerList_PortClient() {
        }
        
        public CustomerList_PortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerList_PortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerList_PortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerList_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AX_CRT_Mage_Connector.Navision_CustomerListService.Read_Result AX_CRT_Mage_Connector.Navision_CustomerListService.CustomerList_Port.Read(AX_CRT_Mage_Connector.Navision_CustomerListService.Read request) {
            return base.Channel.Read(request);
        }
        
        public AX_CRT_Mage_Connector.Navision_CustomerListService.CustomerList Read(string No) {
            AX_CRT_Mage_Connector.Navision_CustomerListService.Read inValue = new AX_CRT_Mage_Connector.Navision_CustomerListService.Read();
            inValue.No = No;
            AX_CRT_Mage_Connector.Navision_CustomerListService.Read_Result retVal = ((AX_CRT_Mage_Connector.Navision_CustomerListService.CustomerList_Port)(this)).Read(inValue);
            return retVal.CustomerList;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AX_CRT_Mage_Connector.Navision_CustomerListService.ReadByRecId_Result AX_CRT_Mage_Connector.Navision_CustomerListService.CustomerList_Port.ReadByRecId(AX_CRT_Mage_Connector.Navision_CustomerListService.ReadByRecId request) {
            return base.Channel.ReadByRecId(request);
        }
        
        public AX_CRT_Mage_Connector.Navision_CustomerListService.CustomerList ReadByRecId(string recId) {
            AX_CRT_Mage_Connector.Navision_CustomerListService.ReadByRecId inValue = new AX_CRT_Mage_Connector.Navision_CustomerListService.ReadByRecId();
            inValue.recId = recId;
            AX_CRT_Mage_Connector.Navision_CustomerListService.ReadByRecId_Result retVal = ((AX_CRT_Mage_Connector.Navision_CustomerListService.CustomerList_Port)(this)).ReadByRecId(inValue);
            return retVal.CustomerList;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AX_CRT_Mage_Connector.Navision_CustomerListService.ReadMultiple_Result AX_CRT_Mage_Connector.Navision_CustomerListService.CustomerList_Port.ReadMultiple(AX_CRT_Mage_Connector.Navision_CustomerListService.ReadMultiple request) {
            return base.Channel.ReadMultiple(request);
        }
        
        public AX_CRT_Mage_Connector.Navision_CustomerListService.CustomerList[] ReadMultiple(AX_CRT_Mage_Connector.Navision_CustomerListService.CustomerList_Filter[] filter, string bookmarkKey, int setSize) {
            AX_CRT_Mage_Connector.Navision_CustomerListService.ReadMultiple inValue = new AX_CRT_Mage_Connector.Navision_CustomerListService.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            AX_CRT_Mage_Connector.Navision_CustomerListService.ReadMultiple_Result retVal = ((AX_CRT_Mage_Connector.Navision_CustomerListService.CustomerList_Port)(this)).ReadMultiple(inValue);
            return retVal.ReadMultiple_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AX_CRT_Mage_Connector.Navision_CustomerListService.IsUpdated_Result AX_CRT_Mage_Connector.Navision_CustomerListService.CustomerList_Port.IsUpdated(AX_CRT_Mage_Connector.Navision_CustomerListService.IsUpdated request) {
            return base.Channel.IsUpdated(request);
        }
        
        public bool IsUpdated(string Key) {
            AX_CRT_Mage_Connector.Navision_CustomerListService.IsUpdated inValue = new AX_CRT_Mage_Connector.Navision_CustomerListService.IsUpdated();
            inValue.Key = Key;
            AX_CRT_Mage_Connector.Navision_CustomerListService.IsUpdated_Result retVal = ((AX_CRT_Mage_Connector.Navision_CustomerListService.CustomerList_Port)(this)).IsUpdated(inValue);
            return retVal.IsUpdated_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AX_CRT_Mage_Connector.Navision_CustomerListService.GetRecIdFromKey_Result AX_CRT_Mage_Connector.Navision_CustomerListService.CustomerList_Port.GetRecIdFromKey(AX_CRT_Mage_Connector.Navision_CustomerListService.GetRecIdFromKey request) {
            return base.Channel.GetRecIdFromKey(request);
        }
        
        public string GetRecIdFromKey(string Key) {
            AX_CRT_Mage_Connector.Navision_CustomerListService.GetRecIdFromKey inValue = new AX_CRT_Mage_Connector.Navision_CustomerListService.GetRecIdFromKey();
            inValue.Key = Key;
            AX_CRT_Mage_Connector.Navision_CustomerListService.GetRecIdFromKey_Result retVal = ((AX_CRT_Mage_Connector.Navision_CustomerListService.CustomerList_Port)(this)).GetRecIdFromKey(inValue);
            return retVal.GetRecIdFromKey_Result1;
        }
    }
}
