//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MNC_Product_Sync.Navision_Shipment {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/page/postedsalesshipment", ConfigurationName="Navision_Shipment.PostedSalesShipment_Port")]
    public interface PostedSalesShipment_Port {
        
        // CODEGEN: Generating message contract since the wrapper name (Read_Result) of message Read_Result does not match the default value (Read)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/postedsalesshipment:Read", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MNC_Product_Sync.Navision_Shipment.Read_Result Read(MNC_Product_Sync.Navision_Shipment.Read request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/postedsalesshipment:Read", ReplyAction="*")]
        System.Threading.Tasks.Task<MNC_Product_Sync.Navision_Shipment.Read_Result> ReadAsync(MNC_Product_Sync.Navision_Shipment.Read request);
        
        // CODEGEN: Generating message contract since the wrapper name (ReadByRecId_Result) of message ReadByRecId_Result does not match the default value (ReadByRecId)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/postedsalesshipment:ReadByRecId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MNC_Product_Sync.Navision_Shipment.ReadByRecId_Result ReadByRecId(MNC_Product_Sync.Navision_Shipment.ReadByRecId request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/postedsalesshipment:ReadByRecId", ReplyAction="*")]
        System.Threading.Tasks.Task<MNC_Product_Sync.Navision_Shipment.ReadByRecId_Result> ReadByRecIdAsync(MNC_Product_Sync.Navision_Shipment.ReadByRecId request);
        
        // CODEGEN: Generating message contract since the wrapper name (ReadMultiple_Result) of message ReadMultiple_Result does not match the default value (ReadMultiple)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/postedsalesshipment:ReadMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MNC_Product_Sync.Navision_Shipment.ReadMultiple_Result ReadMultiple(MNC_Product_Sync.Navision_Shipment.ReadMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/postedsalesshipment:ReadMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<MNC_Product_Sync.Navision_Shipment.ReadMultiple_Result> ReadMultipleAsync(MNC_Product_Sync.Navision_Shipment.ReadMultiple request);
        
        // CODEGEN: Generating message contract since the wrapper name (IsUpdated_Result) of message IsUpdated_Result does not match the default value (IsUpdated)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/postedsalesshipment:IsUpdated", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MNC_Product_Sync.Navision_Shipment.IsUpdated_Result IsUpdated(MNC_Product_Sync.Navision_Shipment.IsUpdated request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/postedsalesshipment:IsUpdated", ReplyAction="*")]
        System.Threading.Tasks.Task<MNC_Product_Sync.Navision_Shipment.IsUpdated_Result> IsUpdatedAsync(MNC_Product_Sync.Navision_Shipment.IsUpdated request);
        
        // CODEGEN: Generating message contract since the wrapper name (GetRecIdFromKey_Result) of message GetRecIdFromKey_Result does not match the default value (GetRecIdFromKey)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/postedsalesshipment:GetRecIdFromKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MNC_Product_Sync.Navision_Shipment.GetRecIdFromKey_Result GetRecIdFromKey(MNC_Product_Sync.Navision_Shipment.GetRecIdFromKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/postedsalesshipment:GetRecIdFromKey", ReplyAction="*")]
        System.Threading.Tasks.Task<MNC_Product_Sync.Navision_Shipment.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(MNC_Product_Sync.Navision_Shipment.GetRecIdFromKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/postedsalesshipment:Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MNC_Product_Sync.Navision_Shipment.Update_Result Update(MNC_Product_Sync.Navision_Shipment.Update request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/postedsalesshipment:Update", ReplyAction="*")]
        System.Threading.Tasks.Task<MNC_Product_Sync.Navision_Shipment.Update_Result> UpdateAsync(MNC_Product_Sync.Navision_Shipment.Update request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/postedsalesshipment:UpdateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MNC_Product_Sync.Navision_Shipment.UpdateMultiple_Result UpdateMultiple(MNC_Product_Sync.Navision_Shipment.UpdateMultiple request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/postedsalesshipment:UpdateMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<MNC_Product_Sync.Navision_Shipment.UpdateMultiple_Result> UpdateMultipleAsync(MNC_Product_Sync.Navision_Shipment.UpdateMultiple request);
        
        // CODEGEN: Generating message contract since the wrapper name (Delete_Result) of message Delete_Result does not match the default value (Delete)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/postedsalesshipment:Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MNC_Product_Sync.Navision_Shipment.Delete_Result Delete(MNC_Product_Sync.Navision_Shipment.Delete request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/postedsalesshipment:Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<MNC_Product_Sync.Navision_Shipment.Delete_Result> DeleteAsync(MNC_Product_Sync.Navision_Shipment.Delete request);
        
        // CODEGEN: Generating message contract since the wrapper name (Delete_SalesShipmLines_Result) of message Delete_SalesShipmLines_Result does not match the default value (Delete_SalesShipmLines)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/postedsalesshipment:Delete_SalesShipmLines", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MNC_Product_Sync.Navision_Shipment.Delete_SalesShipmLines_Result Delete_SalesShipmLines(MNC_Product_Sync.Navision_Shipment.Delete_SalesShipmLines request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/postedsalesshipment:Delete_SalesShipmLines", ReplyAction="*")]
        System.Threading.Tasks.Task<MNC_Product_Sync.Navision_Shipment.Delete_SalesShipmLines_Result> Delete_SalesShipmLinesAsync(MNC_Product_Sync.Navision_Shipment.Delete_SalesShipmLines request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/postedsalesshipment")]
    public partial class PostedSalesShipment : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string noField;
        
        private string sell_to_Customer_NoField;
        
        private string sell_to_Contact_NoField;
        
        private string sell_to_Customer_NameField;
        
        private string sell_to_AddressField;
        
        private string sell_to_Address_2Field;
        
        private string sell_to_Post_CodeField;
        
        private string sell_to_CityField;
        
        private string sell_to_ContactField;
        
        private int no_PrintedField;
        
        private bool no_PrintedFieldSpecified;
        
        private string structureField;
        
        private System.DateTime posting_DateField;
        
        private bool posting_DateFieldSpecified;
        
        private System.DateTime document_DateField;
        
        private bool document_DateFieldSpecified;
        
        private System.DateTime requested_Delivery_DateField;
        
        private bool requested_Delivery_DateFieldSpecified;
        
        private System.DateTime promised_Delivery_DateField;
        
        private bool promised_Delivery_DateFieldSpecified;
        
        private string quote_NoField;
        
        private string order_NoField;
        
        private string external_Document_NoField;
        
        private string salesperson_CodeField;
        
        private string responsibility_CenterField;
        
        private string bill_to_Customer_NoField;
        
        private string bill_to_Contact_NoField;
        
        private string bill_to_NameField;
        
        private string bill_to_AddressField;
        
        private string bill_to_Address_2Field;
        
        private string bill_to_Post_CodeField;
        
        private string bill_to_CityField;
        
        private string bill_to_ContactField;
        
        private string shortcut_Dimension_1_CodeField;
        
        private string shortcut_Dimension_2_CodeField;
        
        private string ship_to_CodeField;
        
        private string ship_to_NameField;
        
        private string ship_to_AddressField;
        
        private string ship_to_Address_2Field;
        
        private string ship_to_Post_CodeField;
        
        private string ship_to_CityField;
        
        private string ship_to_ContactField;
        
        private bool transit_DocumentField;
        
        private bool transit_DocumentFieldSpecified;
        
        private string location_CodeField;
        
        private string outbound_Whse_Handling_TimeField;
        
        private string shipping_TimeField;
        
        private string shipment_Method_CodeField;
        
        private string shipping_Agent_CodeField;
        
        private string shipping_Agent_Service_CodeField;
        
        private string package_Tracking_NoField;
        
        private System.DateTime shipment_DateField;
        
        private bool shipment_DateFieldSpecified;
        
        private System.DateTime time_of_RemovalField;
        
        private bool time_of_RemovalFieldSpecified;
        
        private string mode_of_TransportField;
        
        private string vehicle_NoField;
        
        private string lR_RR_NoField;
        
        private System.DateTime lR_RR_DateField;
        
        private bool lR_RR_DateFieldSpecified;
        
        private Posted_Sales_Shpt_Line[] salesShipmLinesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
                this.RaisePropertyChanged("No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Sell_to_Customer_No {
            get {
                return this.sell_to_Customer_NoField;
            }
            set {
                this.sell_to_Customer_NoField = value;
                this.RaisePropertyChanged("Sell_to_Customer_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Sell_to_Contact_No {
            get {
                return this.sell_to_Contact_NoField;
            }
            set {
                this.sell_to_Contact_NoField = value;
                this.RaisePropertyChanged("Sell_to_Contact_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Sell_to_Customer_Name {
            get {
                return this.sell_to_Customer_NameField;
            }
            set {
                this.sell_to_Customer_NameField = value;
                this.RaisePropertyChanged("Sell_to_Customer_Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Sell_to_Address {
            get {
                return this.sell_to_AddressField;
            }
            set {
                this.sell_to_AddressField = value;
                this.RaisePropertyChanged("Sell_to_Address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Sell_to_Address_2 {
            get {
                return this.sell_to_Address_2Field;
            }
            set {
                this.sell_to_Address_2Field = value;
                this.RaisePropertyChanged("Sell_to_Address_2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Sell_to_Post_Code {
            get {
                return this.sell_to_Post_CodeField;
            }
            set {
                this.sell_to_Post_CodeField = value;
                this.RaisePropertyChanged("Sell_to_Post_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Sell_to_City {
            get {
                return this.sell_to_CityField;
            }
            set {
                this.sell_to_CityField = value;
                this.RaisePropertyChanged("Sell_to_City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Sell_to_Contact {
            get {
                return this.sell_to_ContactField;
            }
            set {
                this.sell_to_ContactField = value;
                this.RaisePropertyChanged("Sell_to_Contact");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int No_Printed {
            get {
                return this.no_PrintedField;
            }
            set {
                this.no_PrintedField = value;
                this.RaisePropertyChanged("No_Printed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool No_PrintedSpecified {
            get {
                return this.no_PrintedFieldSpecified;
            }
            set {
                this.no_PrintedFieldSpecified = value;
                this.RaisePropertyChanged("No_PrintedSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Structure {
            get {
                return this.structureField;
            }
            set {
                this.structureField = value;
                this.RaisePropertyChanged("Structure");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=12)]
        public System.DateTime Posting_Date {
            get {
                return this.posting_DateField;
            }
            set {
                this.posting_DateField = value;
                this.RaisePropertyChanged("Posting_Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Posting_DateSpecified {
            get {
                return this.posting_DateFieldSpecified;
            }
            set {
                this.posting_DateFieldSpecified = value;
                this.RaisePropertyChanged("Posting_DateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=13)]
        public System.DateTime Document_Date {
            get {
                return this.document_DateField;
            }
            set {
                this.document_DateField = value;
                this.RaisePropertyChanged("Document_Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Document_DateSpecified {
            get {
                return this.document_DateFieldSpecified;
            }
            set {
                this.document_DateFieldSpecified = value;
                this.RaisePropertyChanged("Document_DateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=14)]
        public System.DateTime Requested_Delivery_Date {
            get {
                return this.requested_Delivery_DateField;
            }
            set {
                this.requested_Delivery_DateField = value;
                this.RaisePropertyChanged("Requested_Delivery_Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Requested_Delivery_DateSpecified {
            get {
                return this.requested_Delivery_DateFieldSpecified;
            }
            set {
                this.requested_Delivery_DateFieldSpecified = value;
                this.RaisePropertyChanged("Requested_Delivery_DateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=15)]
        public System.DateTime Promised_Delivery_Date {
            get {
                return this.promised_Delivery_DateField;
            }
            set {
                this.promised_Delivery_DateField = value;
                this.RaisePropertyChanged("Promised_Delivery_Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Promised_Delivery_DateSpecified {
            get {
                return this.promised_Delivery_DateFieldSpecified;
            }
            set {
                this.promised_Delivery_DateFieldSpecified = value;
                this.RaisePropertyChanged("Promised_Delivery_DateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string Quote_No {
            get {
                return this.quote_NoField;
            }
            set {
                this.quote_NoField = value;
                this.RaisePropertyChanged("Quote_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string Order_No {
            get {
                return this.order_NoField;
            }
            set {
                this.order_NoField = value;
                this.RaisePropertyChanged("Order_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string External_Document_No {
            get {
                return this.external_Document_NoField;
            }
            set {
                this.external_Document_NoField = value;
                this.RaisePropertyChanged("External_Document_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string Salesperson_Code {
            get {
                return this.salesperson_CodeField;
            }
            set {
                this.salesperson_CodeField = value;
                this.RaisePropertyChanged("Salesperson_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string Responsibility_Center {
            get {
                return this.responsibility_CenterField;
            }
            set {
                this.responsibility_CenterField = value;
                this.RaisePropertyChanged("Responsibility_Center");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string Bill_to_Customer_No {
            get {
                return this.bill_to_Customer_NoField;
            }
            set {
                this.bill_to_Customer_NoField = value;
                this.RaisePropertyChanged("Bill_to_Customer_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string Bill_to_Contact_No {
            get {
                return this.bill_to_Contact_NoField;
            }
            set {
                this.bill_to_Contact_NoField = value;
                this.RaisePropertyChanged("Bill_to_Contact_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string Bill_to_Name {
            get {
                return this.bill_to_NameField;
            }
            set {
                this.bill_to_NameField = value;
                this.RaisePropertyChanged("Bill_to_Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string Bill_to_Address {
            get {
                return this.bill_to_AddressField;
            }
            set {
                this.bill_to_AddressField = value;
                this.RaisePropertyChanged("Bill_to_Address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string Bill_to_Address_2 {
            get {
                return this.bill_to_Address_2Field;
            }
            set {
                this.bill_to_Address_2Field = value;
                this.RaisePropertyChanged("Bill_to_Address_2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string Bill_to_Post_Code {
            get {
                return this.bill_to_Post_CodeField;
            }
            set {
                this.bill_to_Post_CodeField = value;
                this.RaisePropertyChanged("Bill_to_Post_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string Bill_to_City {
            get {
                return this.bill_to_CityField;
            }
            set {
                this.bill_to_CityField = value;
                this.RaisePropertyChanged("Bill_to_City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string Bill_to_Contact {
            get {
                return this.bill_to_ContactField;
            }
            set {
                this.bill_to_ContactField = value;
                this.RaisePropertyChanged("Bill_to_Contact");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string Shortcut_Dimension_1_Code {
            get {
                return this.shortcut_Dimension_1_CodeField;
            }
            set {
                this.shortcut_Dimension_1_CodeField = value;
                this.RaisePropertyChanged("Shortcut_Dimension_1_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string Shortcut_Dimension_2_Code {
            get {
                return this.shortcut_Dimension_2_CodeField;
            }
            set {
                this.shortcut_Dimension_2_CodeField = value;
                this.RaisePropertyChanged("Shortcut_Dimension_2_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string Ship_to_Code {
            get {
                return this.ship_to_CodeField;
            }
            set {
                this.ship_to_CodeField = value;
                this.RaisePropertyChanged("Ship_to_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string Ship_to_Name {
            get {
                return this.ship_to_NameField;
            }
            set {
                this.ship_to_NameField = value;
                this.RaisePropertyChanged("Ship_to_Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string Ship_to_Address {
            get {
                return this.ship_to_AddressField;
            }
            set {
                this.ship_to_AddressField = value;
                this.RaisePropertyChanged("Ship_to_Address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public string Ship_to_Address_2 {
            get {
                return this.ship_to_Address_2Field;
            }
            set {
                this.ship_to_Address_2Field = value;
                this.RaisePropertyChanged("Ship_to_Address_2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public string Ship_to_Post_Code {
            get {
                return this.ship_to_Post_CodeField;
            }
            set {
                this.ship_to_Post_CodeField = value;
                this.RaisePropertyChanged("Ship_to_Post_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public string Ship_to_City {
            get {
                return this.ship_to_CityField;
            }
            set {
                this.ship_to_CityField = value;
                this.RaisePropertyChanged("Ship_to_City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public string Ship_to_Contact {
            get {
                return this.ship_to_ContactField;
            }
            set {
                this.ship_to_ContactField = value;
                this.RaisePropertyChanged("Ship_to_Contact");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public bool Transit_Document {
            get {
                return this.transit_DocumentField;
            }
            set {
                this.transit_DocumentField = value;
                this.RaisePropertyChanged("Transit_Document");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Transit_DocumentSpecified {
            get {
                return this.transit_DocumentFieldSpecified;
            }
            set {
                this.transit_DocumentFieldSpecified = value;
                this.RaisePropertyChanged("Transit_DocumentSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        public string Location_Code {
            get {
                return this.location_CodeField;
            }
            set {
                this.location_CodeField = value;
                this.RaisePropertyChanged("Location_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=40)]
        public string Outbound_Whse_Handling_Time {
            get {
                return this.outbound_Whse_Handling_TimeField;
            }
            set {
                this.outbound_Whse_Handling_TimeField = value;
                this.RaisePropertyChanged("Outbound_Whse_Handling_Time");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=41)]
        public string Shipping_Time {
            get {
                return this.shipping_TimeField;
            }
            set {
                this.shipping_TimeField = value;
                this.RaisePropertyChanged("Shipping_Time");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=42)]
        public string Shipment_Method_Code {
            get {
                return this.shipment_Method_CodeField;
            }
            set {
                this.shipment_Method_CodeField = value;
                this.RaisePropertyChanged("Shipment_Method_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=43)]
        public string Shipping_Agent_Code {
            get {
                return this.shipping_Agent_CodeField;
            }
            set {
                this.shipping_Agent_CodeField = value;
                this.RaisePropertyChanged("Shipping_Agent_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=44)]
        public string Shipping_Agent_Service_Code {
            get {
                return this.shipping_Agent_Service_CodeField;
            }
            set {
                this.shipping_Agent_Service_CodeField = value;
                this.RaisePropertyChanged("Shipping_Agent_Service_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=45)]
        public string Package_Tracking_No {
            get {
                return this.package_Tracking_NoField;
            }
            set {
                this.package_Tracking_NoField = value;
                this.RaisePropertyChanged("Package_Tracking_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=46)]
        public System.DateTime Shipment_Date {
            get {
                return this.shipment_DateField;
            }
            set {
                this.shipment_DateField = value;
                this.RaisePropertyChanged("Shipment_Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Shipment_DateSpecified {
            get {
                return this.shipment_DateFieldSpecified;
            }
            set {
                this.shipment_DateFieldSpecified = value;
                this.RaisePropertyChanged("Shipment_DateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="time", Order=47)]
        public System.DateTime Time_of_Removal {
            get {
                return this.time_of_RemovalField;
            }
            set {
                this.time_of_RemovalField = value;
                this.RaisePropertyChanged("Time_of_Removal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Time_of_RemovalSpecified {
            get {
                return this.time_of_RemovalFieldSpecified;
            }
            set {
                this.time_of_RemovalFieldSpecified = value;
                this.RaisePropertyChanged("Time_of_RemovalSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=48)]
        public string Mode_of_Transport {
            get {
                return this.mode_of_TransportField;
            }
            set {
                this.mode_of_TransportField = value;
                this.RaisePropertyChanged("Mode_of_Transport");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=49)]
        public string Vehicle_No {
            get {
                return this.vehicle_NoField;
            }
            set {
                this.vehicle_NoField = value;
                this.RaisePropertyChanged("Vehicle_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=50)]
        public string LR_RR_No {
            get {
                return this.lR_RR_NoField;
            }
            set {
                this.lR_RR_NoField = value;
                this.RaisePropertyChanged("LR_RR_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=51)]
        public System.DateTime LR_RR_Date {
            get {
                return this.lR_RR_DateField;
            }
            set {
                this.lR_RR_DateField = value;
                this.RaisePropertyChanged("LR_RR_Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LR_RR_DateSpecified {
            get {
                return this.lR_RR_DateFieldSpecified;
            }
            set {
                this.lR_RR_DateFieldSpecified = value;
                this.RaisePropertyChanged("LR_RR_DateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=52)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Posted_Sales_Shpt_Line[] SalesShipmLines {
            get {
                return this.salesShipmLinesField;
            }
            set {
                this.salesShipmLinesField = value;
                this.RaisePropertyChanged("SalesShipmLines");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/postedsalesshipment")]
    public partial class Posted_Sales_Shpt_Line : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private Type typeField;
        
        private bool typeFieldSpecified;
        
        private string noField;
        
        private string cross_Reference_NoField;
        
        private string variant_CodeField;
        
        private string descriptionField;
        
        private decimal unit_PriceField;
        
        private bool unit_PriceFieldSpecified;
        
        private decimal amount_Including_ExciseField;
        
        private bool amount_Including_ExciseFieldSpecified;
        
        private string service_Tax_GroupField;
        
        private string return_Reason_CodeField;
        
        private string location_CodeField;
        
        private string bin_CodeField;
        
        private decimal quantityField;
        
        private bool quantityFieldSpecified;
        
        private string unit_of_Measure_CodeField;
        
        private string unit_of_MeasureField;
        
        private decimal quantity_InvoicedField;
        
        private bool quantity_InvoicedFieldSpecified;
        
        private decimal qty_Shipped_Not_InvoicedField;
        
        private bool qty_Shipped_Not_InvoicedFieldSpecified;
        
        private System.DateTime requested_Delivery_DateField;
        
        private bool requested_Delivery_DateFieldSpecified;
        
        private System.DateTime promised_Delivery_DateField;
        
        private bool promised_Delivery_DateFieldSpecified;
        
        private System.DateTime planned_Delivery_DateField;
        
        private bool planned_Delivery_DateFieldSpecified;
        
        private System.DateTime planned_Shipment_DateField;
        
        private bool planned_Shipment_DateFieldSpecified;
        
        private System.DateTime shipment_DateField;
        
        private bool shipment_DateFieldSpecified;
        
        private string shipping_TimeField;
        
        private string job_NoField;
        
        private string outbound_Whse_Handling_TimeField;
        
        private int appl_to_Item_EntryField;
        
        private bool appl_to_Item_EntryFieldSpecified;
        
        private string shortcut_Dimension_1_CodeField;
        
        private string shortcut_Dimension_2_CodeField;
        
        private bool correctionField;
        
        private bool correctionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Type Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
                this.RaisePropertyChanged("TypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
                this.RaisePropertyChanged("No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Cross_Reference_No {
            get {
                return this.cross_Reference_NoField;
            }
            set {
                this.cross_Reference_NoField = value;
                this.RaisePropertyChanged("Cross_Reference_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Variant_Code {
            get {
                return this.variant_CodeField;
            }
            set {
                this.variant_CodeField = value;
                this.RaisePropertyChanged("Variant_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public decimal Unit_Price {
            get {
                return this.unit_PriceField;
            }
            set {
                this.unit_PriceField = value;
                this.RaisePropertyChanged("Unit_Price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Unit_PriceSpecified {
            get {
                return this.unit_PriceFieldSpecified;
            }
            set {
                this.unit_PriceFieldSpecified = value;
                this.RaisePropertyChanged("Unit_PriceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public decimal Amount_Including_Excise {
            get {
                return this.amount_Including_ExciseField;
            }
            set {
                this.amount_Including_ExciseField = value;
                this.RaisePropertyChanged("Amount_Including_Excise");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Amount_Including_ExciseSpecified {
            get {
                return this.amount_Including_ExciseFieldSpecified;
            }
            set {
                this.amount_Including_ExciseFieldSpecified = value;
                this.RaisePropertyChanged("Amount_Including_ExciseSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Service_Tax_Group {
            get {
                return this.service_Tax_GroupField;
            }
            set {
                this.service_Tax_GroupField = value;
                this.RaisePropertyChanged("Service_Tax_Group");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Return_Reason_Code {
            get {
                return this.return_Reason_CodeField;
            }
            set {
                this.return_Reason_CodeField = value;
                this.RaisePropertyChanged("Return_Reason_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Location_Code {
            get {
                return this.location_CodeField;
            }
            set {
                this.location_CodeField = value;
                this.RaisePropertyChanged("Location_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Bin_Code {
            get {
                return this.bin_CodeField;
            }
            set {
                this.bin_CodeField = value;
                this.RaisePropertyChanged("Bin_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public decimal Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
                this.RaisePropertyChanged("Quantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QuantitySpecified {
            get {
                return this.quantityFieldSpecified;
            }
            set {
                this.quantityFieldSpecified = value;
                this.RaisePropertyChanged("QuantitySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Unit_of_Measure_Code {
            get {
                return this.unit_of_Measure_CodeField;
            }
            set {
                this.unit_of_Measure_CodeField = value;
                this.RaisePropertyChanged("Unit_of_Measure_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Unit_of_Measure {
            get {
                return this.unit_of_MeasureField;
            }
            set {
                this.unit_of_MeasureField = value;
                this.RaisePropertyChanged("Unit_of_Measure");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public decimal Quantity_Invoiced {
            get {
                return this.quantity_InvoicedField;
            }
            set {
                this.quantity_InvoicedField = value;
                this.RaisePropertyChanged("Quantity_Invoiced");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Quantity_InvoicedSpecified {
            get {
                return this.quantity_InvoicedFieldSpecified;
            }
            set {
                this.quantity_InvoicedFieldSpecified = value;
                this.RaisePropertyChanged("Quantity_InvoicedSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public decimal Qty_Shipped_Not_Invoiced {
            get {
                return this.qty_Shipped_Not_InvoicedField;
            }
            set {
                this.qty_Shipped_Not_InvoicedField = value;
                this.RaisePropertyChanged("Qty_Shipped_Not_Invoiced");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Qty_Shipped_Not_InvoicedSpecified {
            get {
                return this.qty_Shipped_Not_InvoicedFieldSpecified;
            }
            set {
                this.qty_Shipped_Not_InvoicedFieldSpecified = value;
                this.RaisePropertyChanged("Qty_Shipped_Not_InvoicedSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=17)]
        public System.DateTime Requested_Delivery_Date {
            get {
                return this.requested_Delivery_DateField;
            }
            set {
                this.requested_Delivery_DateField = value;
                this.RaisePropertyChanged("Requested_Delivery_Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Requested_Delivery_DateSpecified {
            get {
                return this.requested_Delivery_DateFieldSpecified;
            }
            set {
                this.requested_Delivery_DateFieldSpecified = value;
                this.RaisePropertyChanged("Requested_Delivery_DateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=18)]
        public System.DateTime Promised_Delivery_Date {
            get {
                return this.promised_Delivery_DateField;
            }
            set {
                this.promised_Delivery_DateField = value;
                this.RaisePropertyChanged("Promised_Delivery_Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Promised_Delivery_DateSpecified {
            get {
                return this.promised_Delivery_DateFieldSpecified;
            }
            set {
                this.promised_Delivery_DateFieldSpecified = value;
                this.RaisePropertyChanged("Promised_Delivery_DateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=19)]
        public System.DateTime Planned_Delivery_Date {
            get {
                return this.planned_Delivery_DateField;
            }
            set {
                this.planned_Delivery_DateField = value;
                this.RaisePropertyChanged("Planned_Delivery_Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Planned_Delivery_DateSpecified {
            get {
                return this.planned_Delivery_DateFieldSpecified;
            }
            set {
                this.planned_Delivery_DateFieldSpecified = value;
                this.RaisePropertyChanged("Planned_Delivery_DateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=20)]
        public System.DateTime Planned_Shipment_Date {
            get {
                return this.planned_Shipment_DateField;
            }
            set {
                this.planned_Shipment_DateField = value;
                this.RaisePropertyChanged("Planned_Shipment_Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Planned_Shipment_DateSpecified {
            get {
                return this.planned_Shipment_DateFieldSpecified;
            }
            set {
                this.planned_Shipment_DateFieldSpecified = value;
                this.RaisePropertyChanged("Planned_Shipment_DateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=21)]
        public System.DateTime Shipment_Date {
            get {
                return this.shipment_DateField;
            }
            set {
                this.shipment_DateField = value;
                this.RaisePropertyChanged("Shipment_Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Shipment_DateSpecified {
            get {
                return this.shipment_DateFieldSpecified;
            }
            set {
                this.shipment_DateFieldSpecified = value;
                this.RaisePropertyChanged("Shipment_DateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string Shipping_Time {
            get {
                return this.shipping_TimeField;
            }
            set {
                this.shipping_TimeField = value;
                this.RaisePropertyChanged("Shipping_Time");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string Job_No {
            get {
                return this.job_NoField;
            }
            set {
                this.job_NoField = value;
                this.RaisePropertyChanged("Job_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string Outbound_Whse_Handling_Time {
            get {
                return this.outbound_Whse_Handling_TimeField;
            }
            set {
                this.outbound_Whse_Handling_TimeField = value;
                this.RaisePropertyChanged("Outbound_Whse_Handling_Time");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public int Appl_to_Item_Entry {
            get {
                return this.appl_to_Item_EntryField;
            }
            set {
                this.appl_to_Item_EntryField = value;
                this.RaisePropertyChanged("Appl_to_Item_Entry");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Appl_to_Item_EntrySpecified {
            get {
                return this.appl_to_Item_EntryFieldSpecified;
            }
            set {
                this.appl_to_Item_EntryFieldSpecified = value;
                this.RaisePropertyChanged("Appl_to_Item_EntrySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string Shortcut_Dimension_1_Code {
            get {
                return this.shortcut_Dimension_1_CodeField;
            }
            set {
                this.shortcut_Dimension_1_CodeField = value;
                this.RaisePropertyChanged("Shortcut_Dimension_1_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string Shortcut_Dimension_2_Code {
            get {
                return this.shortcut_Dimension_2_CodeField;
            }
            set {
                this.shortcut_Dimension_2_CodeField = value;
                this.RaisePropertyChanged("Shortcut_Dimension_2_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public bool Correction {
            get {
                return this.correctionField;
            }
            set {
                this.correctionField = value;
                this.RaisePropertyChanged("Correction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CorrectionSpecified {
            get {
                return this.correctionFieldSpecified;
            }
            set {
                this.correctionFieldSpecified = value;
                this.RaisePropertyChanged("CorrectionSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/postedsalesshipment")]
    public enum Type {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        G_L_Account,
        
        /// <remarks/>
        Item,
        
        /// <remarks/>
        Resource,
        
        /// <remarks/>
        Fixed_Asset,
        
        /// <remarks/>
        Charge_Item,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/postedsalesshipment")]
    public partial class PostedSalesShipment_Filter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PostedSalesShipment_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public PostedSalesShipment_Fields Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
                this.RaisePropertyChanged("Field");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
                this.RaisePropertyChanged("Criteria");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/postedsalesshipment")]
    public enum PostedSalesShipment_Fields {
        
        /// <remarks/>
        No,
        
        /// <remarks/>
        Sell_to_Customer_No,
        
        /// <remarks/>
        Sell_to_Contact_No,
        
        /// <remarks/>
        Sell_to_Customer_Name,
        
        /// <remarks/>
        Sell_to_Address,
        
        /// <remarks/>
        Sell_to_Address_2,
        
        /// <remarks/>
        Sell_to_Post_Code,
        
        /// <remarks/>
        Sell_to_City,
        
        /// <remarks/>
        Sell_to_Contact,
        
        /// <remarks/>
        No_Printed,
        
        /// <remarks/>
        Structure,
        
        /// <remarks/>
        Posting_Date,
        
        /// <remarks/>
        Document_Date,
        
        /// <remarks/>
        Requested_Delivery_Date,
        
        /// <remarks/>
        Promised_Delivery_Date,
        
        /// <remarks/>
        Quote_No,
        
        /// <remarks/>
        Order_No,
        
        /// <remarks/>
        External_Document_No,
        
        /// <remarks/>
        Salesperson_Code,
        
        /// <remarks/>
        Responsibility_Center,
        
        /// <remarks/>
        Bill_to_Customer_No,
        
        /// <remarks/>
        Bill_to_Contact_No,
        
        /// <remarks/>
        Bill_to_Name,
        
        /// <remarks/>
        Bill_to_Address,
        
        /// <remarks/>
        Bill_to_Address_2,
        
        /// <remarks/>
        Bill_to_Post_Code,
        
        /// <remarks/>
        Bill_to_City,
        
        /// <remarks/>
        Bill_to_Contact,
        
        /// <remarks/>
        Shortcut_Dimension_1_Code,
        
        /// <remarks/>
        Shortcut_Dimension_2_Code,
        
        /// <remarks/>
        Ship_to_Code,
        
        /// <remarks/>
        Ship_to_Name,
        
        /// <remarks/>
        Ship_to_Address,
        
        /// <remarks/>
        Ship_to_Address_2,
        
        /// <remarks/>
        Ship_to_Post_Code,
        
        /// <remarks/>
        Ship_to_City,
        
        /// <remarks/>
        Ship_to_Contact,
        
        /// <remarks/>
        Transit_Document,
        
        /// <remarks/>
        Location_Code,
        
        /// <remarks/>
        Outbound_Whse_Handling_Time,
        
        /// <remarks/>
        Shipping_Time,
        
        /// <remarks/>
        Shipment_Method_Code,
        
        /// <remarks/>
        Shipping_Agent_Code,
        
        /// <remarks/>
        Shipping_Agent_Service_Code,
        
        /// <remarks/>
        Package_Tracking_No,
        
        /// <remarks/>
        Shipment_Date,
        
        /// <remarks/>
        Time_of_Removal,
        
        /// <remarks/>
        Mode_of_Transport,
        
        /// <remarks/>
        Vehicle_No,
        
        /// <remarks/>
        LR_RR_No,
        
        /// <remarks/>
        LR_RR_Date,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read", WrapperNamespace="urn:microsoft-dynamics-schemas/page/postedsalesshipment", IsWrapped=true)]
    public partial class Read {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/postedsalesshipment", Order=0)]
        public string No;
        
        public Read() {
        }
        
        public Read(string No) {
            this.No = No;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/postedsalesshipment", IsWrapped=true)]
    public partial class Read_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/postedsalesshipment", Order=0)]
        public MNC_Product_Sync.Navision_Shipment.PostedSalesShipment PostedSalesShipment;
        
        public Read_Result() {
        }
        
        public Read_Result(MNC_Product_Sync.Navision_Shipment.PostedSalesShipment PostedSalesShipment) {
            this.PostedSalesShipment = PostedSalesShipment;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId", WrapperNamespace="urn:microsoft-dynamics-schemas/page/postedsalesshipment", IsWrapped=true)]
    public partial class ReadByRecId {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/postedsalesshipment", Order=0)]
        public string recId;
        
        public ReadByRecId() {
        }
        
        public ReadByRecId(string recId) {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/postedsalesshipment", IsWrapped=true)]
    public partial class ReadByRecId_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/postedsalesshipment", Order=0)]
        public MNC_Product_Sync.Navision_Shipment.PostedSalesShipment PostedSalesShipment;
        
        public ReadByRecId_Result() {
        }
        
        public ReadByRecId_Result(MNC_Product_Sync.Navision_Shipment.PostedSalesShipment PostedSalesShipment) {
            this.PostedSalesShipment = PostedSalesShipment;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/postedsalesshipment", IsWrapped=true)]
    public partial class ReadMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/postedsalesshipment", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("filter")]
        public MNC_Product_Sync.Navision_Shipment.PostedSalesShipment_Filter[] filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/postedsalesshipment", Order=1)]
        public string bookmarkKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/postedsalesshipment", Order=2)]
        public int setSize;
        
        public ReadMultiple() {
        }
        
        public ReadMultiple(MNC_Product_Sync.Navision_Shipment.PostedSalesShipment_Filter[] filter, string bookmarkKey, int setSize) {
            this.filter = filter;
            this.bookmarkKey = bookmarkKey;
            this.setSize = setSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/postedsalesshipment", IsWrapped=true)]
    public partial class ReadMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadMultiple_Result", Namespace="urn:microsoft-dynamics-schemas/page/postedsalesshipment", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public MNC_Product_Sync.Navision_Shipment.PostedSalesShipment[] ReadMultiple_Result1;
        
        public ReadMultiple_Result() {
        }
        
        public ReadMultiple_Result(MNC_Product_Sync.Navision_Shipment.PostedSalesShipment[] ReadMultiple_Result1) {
            this.ReadMultiple_Result1 = ReadMultiple_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated", WrapperNamespace="urn:microsoft-dynamics-schemas/page/postedsalesshipment", IsWrapped=true)]
    public partial class IsUpdated {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/postedsalesshipment", Order=0)]
        public string Key;
        
        public IsUpdated() {
        }
        
        public IsUpdated(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/postedsalesshipment", IsWrapped=true)]
    public partial class IsUpdated_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUpdated_Result", Namespace="urn:microsoft-dynamics-schemas/page/postedsalesshipment", Order=0)]
        public bool IsUpdated_Result1;
        
        public IsUpdated_Result() {
        }
        
        public IsUpdated_Result(bool IsUpdated_Result1) {
            this.IsUpdated_Result1 = IsUpdated_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey", WrapperNamespace="urn:microsoft-dynamics-schemas/page/postedsalesshipment", IsWrapped=true)]
    public partial class GetRecIdFromKey {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/postedsalesshipment", Order=0)]
        public string Key;
        
        public GetRecIdFromKey() {
        }
        
        public GetRecIdFromKey(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/postedsalesshipment", IsWrapped=true)]
    public partial class GetRecIdFromKey_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecIdFromKey_Result", Namespace="urn:microsoft-dynamics-schemas/page/postedsalesshipment", Order=0)]
        public string GetRecIdFromKey_Result1;
        
        public GetRecIdFromKey_Result() {
        }
        
        public GetRecIdFromKey_Result(string GetRecIdFromKey_Result1) {
            this.GetRecIdFromKey_Result1 = GetRecIdFromKey_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update", WrapperNamespace="urn:microsoft-dynamics-schemas/page/postedsalesshipment", IsWrapped=true)]
    public partial class Update {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/postedsalesshipment", Order=0)]
        public MNC_Product_Sync.Navision_Shipment.PostedSalesShipment PostedSalesShipment;
        
        public Update() {
        }
        
        public Update(MNC_Product_Sync.Navision_Shipment.PostedSalesShipment PostedSalesShipment) {
            this.PostedSalesShipment = PostedSalesShipment;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/postedsalesshipment", IsWrapped=true)]
    public partial class Update_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/postedsalesshipment", Order=0)]
        public MNC_Product_Sync.Navision_Shipment.PostedSalesShipment PostedSalesShipment;
        
        public Update_Result() {
        }
        
        public Update_Result(MNC_Product_Sync.Navision_Shipment.PostedSalesShipment PostedSalesShipment) {
            this.PostedSalesShipment = PostedSalesShipment;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/postedsalesshipment", IsWrapped=true)]
    public partial class UpdateMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/postedsalesshipment", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public MNC_Product_Sync.Navision_Shipment.PostedSalesShipment[] PostedSalesShipment_List;
        
        public UpdateMultiple() {
        }
        
        public UpdateMultiple(MNC_Product_Sync.Navision_Shipment.PostedSalesShipment[] PostedSalesShipment_List) {
            this.PostedSalesShipment_List = PostedSalesShipment_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/postedsalesshipment", IsWrapped=true)]
    public partial class UpdateMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/postedsalesshipment", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public MNC_Product_Sync.Navision_Shipment.PostedSalesShipment[] PostedSalesShipment_List;
        
        public UpdateMultiple_Result() {
        }
        
        public UpdateMultiple_Result(MNC_Product_Sync.Navision_Shipment.PostedSalesShipment[] PostedSalesShipment_List) {
            this.PostedSalesShipment_List = PostedSalesShipment_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete", WrapperNamespace="urn:microsoft-dynamics-schemas/page/postedsalesshipment", IsWrapped=true)]
    public partial class Delete {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/postedsalesshipment", Order=0)]
        public string Key;
        
        public Delete() {
        }
        
        public Delete(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/postedsalesshipment", IsWrapped=true)]
    public partial class Delete_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete_Result", Namespace="urn:microsoft-dynamics-schemas/page/postedsalesshipment", Order=0)]
        public bool Delete_Result1;
        
        public Delete_Result() {
        }
        
        public Delete_Result(bool Delete_Result1) {
            this.Delete_Result1 = Delete_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete_SalesShipmLines", WrapperNamespace="urn:microsoft-dynamics-schemas/page/postedsalesshipment", IsWrapped=true)]
    public partial class Delete_SalesShipmLines {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/postedsalesshipment", Order=0)]
        public string SalesShipmLines_Key;
        
        public Delete_SalesShipmLines() {
        }
        
        public Delete_SalesShipmLines(string SalesShipmLines_Key) {
            this.SalesShipmLines_Key = SalesShipmLines_Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete_SalesShipmLines_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/postedsalesshipment", IsWrapped=true)]
    public partial class Delete_SalesShipmLines_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete_SalesShipmLines_Result", Namespace="urn:microsoft-dynamics-schemas/page/postedsalesshipment", Order=0)]
        public bool Delete_SalesShipmLines_Result1;
        
        public Delete_SalesShipmLines_Result() {
        }
        
        public Delete_SalesShipmLines_Result(bool Delete_SalesShipmLines_Result1) {
            this.Delete_SalesShipmLines_Result1 = Delete_SalesShipmLines_Result1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PostedSalesShipment_PortChannel : MNC_Product_Sync.Navision_Shipment.PostedSalesShipment_Port, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PostedSalesShipment_PortClient : System.ServiceModel.ClientBase<MNC_Product_Sync.Navision_Shipment.PostedSalesShipment_Port>, MNC_Product_Sync.Navision_Shipment.PostedSalesShipment_Port {
        
        public PostedSalesShipment_PortClient() {
        }
        
        public PostedSalesShipment_PortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PostedSalesShipment_PortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PostedSalesShipment_PortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PostedSalesShipment_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MNC_Product_Sync.Navision_Shipment.Read_Result MNC_Product_Sync.Navision_Shipment.PostedSalesShipment_Port.Read(MNC_Product_Sync.Navision_Shipment.Read request) {
            return base.Channel.Read(request);
        }
        
        public MNC_Product_Sync.Navision_Shipment.PostedSalesShipment Read(string No) {
            MNC_Product_Sync.Navision_Shipment.Read inValue = new MNC_Product_Sync.Navision_Shipment.Read();
            inValue.No = No;
            MNC_Product_Sync.Navision_Shipment.Read_Result retVal = ((MNC_Product_Sync.Navision_Shipment.PostedSalesShipment_Port)(this)).Read(inValue);
            return retVal.PostedSalesShipment;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MNC_Product_Sync.Navision_Shipment.Read_Result> MNC_Product_Sync.Navision_Shipment.PostedSalesShipment_Port.ReadAsync(MNC_Product_Sync.Navision_Shipment.Read request) {
            return base.Channel.ReadAsync(request);
        }
        
        public System.Threading.Tasks.Task<MNC_Product_Sync.Navision_Shipment.Read_Result> ReadAsync(string No) {
            MNC_Product_Sync.Navision_Shipment.Read inValue = new MNC_Product_Sync.Navision_Shipment.Read();
            inValue.No = No;
            return ((MNC_Product_Sync.Navision_Shipment.PostedSalesShipment_Port)(this)).ReadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MNC_Product_Sync.Navision_Shipment.ReadByRecId_Result MNC_Product_Sync.Navision_Shipment.PostedSalesShipment_Port.ReadByRecId(MNC_Product_Sync.Navision_Shipment.ReadByRecId request) {
            return base.Channel.ReadByRecId(request);
        }
        
        public MNC_Product_Sync.Navision_Shipment.PostedSalesShipment ReadByRecId(string recId) {
            MNC_Product_Sync.Navision_Shipment.ReadByRecId inValue = new MNC_Product_Sync.Navision_Shipment.ReadByRecId();
            inValue.recId = recId;
            MNC_Product_Sync.Navision_Shipment.ReadByRecId_Result retVal = ((MNC_Product_Sync.Navision_Shipment.PostedSalesShipment_Port)(this)).ReadByRecId(inValue);
            return retVal.PostedSalesShipment;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MNC_Product_Sync.Navision_Shipment.ReadByRecId_Result> MNC_Product_Sync.Navision_Shipment.PostedSalesShipment_Port.ReadByRecIdAsync(MNC_Product_Sync.Navision_Shipment.ReadByRecId request) {
            return base.Channel.ReadByRecIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<MNC_Product_Sync.Navision_Shipment.ReadByRecId_Result> ReadByRecIdAsync(string recId) {
            MNC_Product_Sync.Navision_Shipment.ReadByRecId inValue = new MNC_Product_Sync.Navision_Shipment.ReadByRecId();
            inValue.recId = recId;
            return ((MNC_Product_Sync.Navision_Shipment.PostedSalesShipment_Port)(this)).ReadByRecIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MNC_Product_Sync.Navision_Shipment.ReadMultiple_Result MNC_Product_Sync.Navision_Shipment.PostedSalesShipment_Port.ReadMultiple(MNC_Product_Sync.Navision_Shipment.ReadMultiple request) {
            return base.Channel.ReadMultiple(request);
        }
        
        public MNC_Product_Sync.Navision_Shipment.PostedSalesShipment[] ReadMultiple(MNC_Product_Sync.Navision_Shipment.PostedSalesShipment_Filter[] filter, string bookmarkKey, int setSize) {
            MNC_Product_Sync.Navision_Shipment.ReadMultiple inValue = new MNC_Product_Sync.Navision_Shipment.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            MNC_Product_Sync.Navision_Shipment.ReadMultiple_Result retVal = ((MNC_Product_Sync.Navision_Shipment.PostedSalesShipment_Port)(this)).ReadMultiple(inValue);
            return retVal.ReadMultiple_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MNC_Product_Sync.Navision_Shipment.ReadMultiple_Result> MNC_Product_Sync.Navision_Shipment.PostedSalesShipment_Port.ReadMultipleAsync(MNC_Product_Sync.Navision_Shipment.ReadMultiple request) {
            return base.Channel.ReadMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<MNC_Product_Sync.Navision_Shipment.ReadMultiple_Result> ReadMultipleAsync(MNC_Product_Sync.Navision_Shipment.PostedSalesShipment_Filter[] filter, string bookmarkKey, int setSize) {
            MNC_Product_Sync.Navision_Shipment.ReadMultiple inValue = new MNC_Product_Sync.Navision_Shipment.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            return ((MNC_Product_Sync.Navision_Shipment.PostedSalesShipment_Port)(this)).ReadMultipleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MNC_Product_Sync.Navision_Shipment.IsUpdated_Result MNC_Product_Sync.Navision_Shipment.PostedSalesShipment_Port.IsUpdated(MNC_Product_Sync.Navision_Shipment.IsUpdated request) {
            return base.Channel.IsUpdated(request);
        }
        
        public bool IsUpdated(string Key) {
            MNC_Product_Sync.Navision_Shipment.IsUpdated inValue = new MNC_Product_Sync.Navision_Shipment.IsUpdated();
            inValue.Key = Key;
            MNC_Product_Sync.Navision_Shipment.IsUpdated_Result retVal = ((MNC_Product_Sync.Navision_Shipment.PostedSalesShipment_Port)(this)).IsUpdated(inValue);
            return retVal.IsUpdated_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MNC_Product_Sync.Navision_Shipment.IsUpdated_Result> MNC_Product_Sync.Navision_Shipment.PostedSalesShipment_Port.IsUpdatedAsync(MNC_Product_Sync.Navision_Shipment.IsUpdated request) {
            return base.Channel.IsUpdatedAsync(request);
        }
        
        public System.Threading.Tasks.Task<MNC_Product_Sync.Navision_Shipment.IsUpdated_Result> IsUpdatedAsync(string Key) {
            MNC_Product_Sync.Navision_Shipment.IsUpdated inValue = new MNC_Product_Sync.Navision_Shipment.IsUpdated();
            inValue.Key = Key;
            return ((MNC_Product_Sync.Navision_Shipment.PostedSalesShipment_Port)(this)).IsUpdatedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MNC_Product_Sync.Navision_Shipment.GetRecIdFromKey_Result MNC_Product_Sync.Navision_Shipment.PostedSalesShipment_Port.GetRecIdFromKey(MNC_Product_Sync.Navision_Shipment.GetRecIdFromKey request) {
            return base.Channel.GetRecIdFromKey(request);
        }
        
        public string GetRecIdFromKey(string Key) {
            MNC_Product_Sync.Navision_Shipment.GetRecIdFromKey inValue = new MNC_Product_Sync.Navision_Shipment.GetRecIdFromKey();
            inValue.Key = Key;
            MNC_Product_Sync.Navision_Shipment.GetRecIdFromKey_Result retVal = ((MNC_Product_Sync.Navision_Shipment.PostedSalesShipment_Port)(this)).GetRecIdFromKey(inValue);
            return retVal.GetRecIdFromKey_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MNC_Product_Sync.Navision_Shipment.GetRecIdFromKey_Result> MNC_Product_Sync.Navision_Shipment.PostedSalesShipment_Port.GetRecIdFromKeyAsync(MNC_Product_Sync.Navision_Shipment.GetRecIdFromKey request) {
            return base.Channel.GetRecIdFromKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<MNC_Product_Sync.Navision_Shipment.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(string Key) {
            MNC_Product_Sync.Navision_Shipment.GetRecIdFromKey inValue = new MNC_Product_Sync.Navision_Shipment.GetRecIdFromKey();
            inValue.Key = Key;
            return ((MNC_Product_Sync.Navision_Shipment.PostedSalesShipment_Port)(this)).GetRecIdFromKeyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MNC_Product_Sync.Navision_Shipment.Update_Result MNC_Product_Sync.Navision_Shipment.PostedSalesShipment_Port.Update(MNC_Product_Sync.Navision_Shipment.Update request) {
            return base.Channel.Update(request);
        }
        
        public void Update(ref MNC_Product_Sync.Navision_Shipment.PostedSalesShipment PostedSalesShipment) {
            MNC_Product_Sync.Navision_Shipment.Update inValue = new MNC_Product_Sync.Navision_Shipment.Update();
            inValue.PostedSalesShipment = PostedSalesShipment;
            MNC_Product_Sync.Navision_Shipment.Update_Result retVal = ((MNC_Product_Sync.Navision_Shipment.PostedSalesShipment_Port)(this)).Update(inValue);
            PostedSalesShipment = retVal.PostedSalesShipment;
        }
        
        public System.Threading.Tasks.Task<MNC_Product_Sync.Navision_Shipment.Update_Result> UpdateAsync(MNC_Product_Sync.Navision_Shipment.Update request) {
            return base.Channel.UpdateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MNC_Product_Sync.Navision_Shipment.UpdateMultiple_Result MNC_Product_Sync.Navision_Shipment.PostedSalesShipment_Port.UpdateMultiple(MNC_Product_Sync.Navision_Shipment.UpdateMultiple request) {
            return base.Channel.UpdateMultiple(request);
        }
        
        public void UpdateMultiple(ref MNC_Product_Sync.Navision_Shipment.PostedSalesShipment[] PostedSalesShipment_List) {
            MNC_Product_Sync.Navision_Shipment.UpdateMultiple inValue = new MNC_Product_Sync.Navision_Shipment.UpdateMultiple();
            inValue.PostedSalesShipment_List = PostedSalesShipment_List;
            MNC_Product_Sync.Navision_Shipment.UpdateMultiple_Result retVal = ((MNC_Product_Sync.Navision_Shipment.PostedSalesShipment_Port)(this)).UpdateMultiple(inValue);
            PostedSalesShipment_List = retVal.PostedSalesShipment_List;
        }
        
        public System.Threading.Tasks.Task<MNC_Product_Sync.Navision_Shipment.UpdateMultiple_Result> UpdateMultipleAsync(MNC_Product_Sync.Navision_Shipment.UpdateMultiple request) {
            return base.Channel.UpdateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MNC_Product_Sync.Navision_Shipment.Delete_Result MNC_Product_Sync.Navision_Shipment.PostedSalesShipment_Port.Delete(MNC_Product_Sync.Navision_Shipment.Delete request) {
            return base.Channel.Delete(request);
        }
        
        public bool Delete(string Key) {
            MNC_Product_Sync.Navision_Shipment.Delete inValue = new MNC_Product_Sync.Navision_Shipment.Delete();
            inValue.Key = Key;
            MNC_Product_Sync.Navision_Shipment.Delete_Result retVal = ((MNC_Product_Sync.Navision_Shipment.PostedSalesShipment_Port)(this)).Delete(inValue);
            return retVal.Delete_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MNC_Product_Sync.Navision_Shipment.Delete_Result> MNC_Product_Sync.Navision_Shipment.PostedSalesShipment_Port.DeleteAsync(MNC_Product_Sync.Navision_Shipment.Delete request) {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<MNC_Product_Sync.Navision_Shipment.Delete_Result> DeleteAsync(string Key) {
            MNC_Product_Sync.Navision_Shipment.Delete inValue = new MNC_Product_Sync.Navision_Shipment.Delete();
            inValue.Key = Key;
            return ((MNC_Product_Sync.Navision_Shipment.PostedSalesShipment_Port)(this)).DeleteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MNC_Product_Sync.Navision_Shipment.Delete_SalesShipmLines_Result MNC_Product_Sync.Navision_Shipment.PostedSalesShipment_Port.Delete_SalesShipmLines(MNC_Product_Sync.Navision_Shipment.Delete_SalesShipmLines request) {
            return base.Channel.Delete_SalesShipmLines(request);
        }
        
        public bool Delete_SalesShipmLines(string SalesShipmLines_Key) {
            MNC_Product_Sync.Navision_Shipment.Delete_SalesShipmLines inValue = new MNC_Product_Sync.Navision_Shipment.Delete_SalesShipmLines();
            inValue.SalesShipmLines_Key = SalesShipmLines_Key;
            MNC_Product_Sync.Navision_Shipment.Delete_SalesShipmLines_Result retVal = ((MNC_Product_Sync.Navision_Shipment.PostedSalesShipment_Port)(this)).Delete_SalesShipmLines(inValue);
            return retVal.Delete_SalesShipmLines_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MNC_Product_Sync.Navision_Shipment.Delete_SalesShipmLines_Result> MNC_Product_Sync.Navision_Shipment.PostedSalesShipment_Port.Delete_SalesShipmLinesAsync(MNC_Product_Sync.Navision_Shipment.Delete_SalesShipmLines request) {
            return base.Channel.Delete_SalesShipmLinesAsync(request);
        }
        
        public System.Threading.Tasks.Task<MNC_Product_Sync.Navision_Shipment.Delete_SalesShipmLines_Result> Delete_SalesShipmLinesAsync(string SalesShipmLines_Key) {
            MNC_Product_Sync.Navision_Shipment.Delete_SalesShipmLines inValue = new MNC_Product_Sync.Navision_Shipment.Delete_SalesShipmLines();
            inValue.SalesShipmLines_Key = SalesShipmLines_Key;
            return ((MNC_Product_Sync.Navision_Shipment.PostedSalesShipment_Port)(this)).Delete_SalesShipmLinesAsync(inValue);
        }
    }
}
