//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AX_CRT_Mage_Connector.Navision_ItemCategory_Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemcategories", ConfigurationName="Navision_ItemCategory_Service.ItemCategories_Port")]
    public interface ItemCategories_Port {
        
        // CODEGEN: Generating message contract since the wrapper name (Read_Result) of message Read_Result does not match the default value (Read)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/itemcategories:Read", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AX_CRT_Mage_Connector.Navision_ItemCategory_Service.Read_Result Read(AX_CRT_Mage_Connector.Navision_ItemCategory_Service.Read request);
        
        // CODEGEN: Generating message contract since the wrapper name (ReadByRecId_Result) of message ReadByRecId_Result does not match the default value (ReadByRecId)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/itemcategories:ReadByRecId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AX_CRT_Mage_Connector.Navision_ItemCategory_Service.ReadByRecId_Result ReadByRecId(AX_CRT_Mage_Connector.Navision_ItemCategory_Service.ReadByRecId request);
        
        // CODEGEN: Generating message contract since the wrapper name (ReadMultiple_Result) of message ReadMultiple_Result does not match the default value (ReadMultiple)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/itemcategories:ReadMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AX_CRT_Mage_Connector.Navision_ItemCategory_Service.ReadMultiple_Result ReadMultiple(AX_CRT_Mage_Connector.Navision_ItemCategory_Service.ReadMultiple request);
        
        // CODEGEN: Generating message contract since the wrapper name (IsUpdated_Result) of message IsUpdated_Result does not match the default value (IsUpdated)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/itemcategories:IsUpdated", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AX_CRT_Mage_Connector.Navision_ItemCategory_Service.IsUpdated_Result IsUpdated(AX_CRT_Mage_Connector.Navision_ItemCategory_Service.IsUpdated request);
        
        // CODEGEN: Generating message contract since the wrapper name (GetRecIdFromKey_Result) of message GetRecIdFromKey_Result does not match the default value (GetRecIdFromKey)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/itemcategories:GetRecIdFromKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AX_CRT_Mage_Connector.Navision_ItemCategory_Service.GetRecIdFromKey_Result GetRecIdFromKey(AX_CRT_Mage_Connector.Navision_ItemCategory_Service.GetRecIdFromKey request);
        
        // CODEGEN: Generating message contract since the wrapper name (Create_Result) of message Create_Result does not match the default value (Create)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/itemcategories:Create", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AX_CRT_Mage_Connector.Navision_ItemCategory_Service.Create_Result Create(AX_CRT_Mage_Connector.Navision_ItemCategory_Service.Create request);
        
        // CODEGEN: Generating message contract since the wrapper name (CreateMultiple_Result) of message CreateMultiple_Result does not match the default value (CreateMultiple)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/itemcategories:CreateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AX_CRT_Mage_Connector.Navision_ItemCategory_Service.CreateMultiple_Result CreateMultiple(AX_CRT_Mage_Connector.Navision_ItemCategory_Service.CreateMultiple request);
        
        // CODEGEN: Generating message contract since the wrapper name (Update_Result) of message Update_Result does not match the default value (Update)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/itemcategories:Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AX_CRT_Mage_Connector.Navision_ItemCategory_Service.Update_Result Update(AX_CRT_Mage_Connector.Navision_ItemCategory_Service.Update request);
        
        // CODEGEN: Generating message contract since the wrapper name (UpdateMultiple_Result) of message UpdateMultiple_Result does not match the default value (UpdateMultiple)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/itemcategories:UpdateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AX_CRT_Mage_Connector.Navision_ItemCategory_Service.UpdateMultiple_Result UpdateMultiple(AX_CRT_Mage_Connector.Navision_ItemCategory_Service.UpdateMultiple request);
        
        // CODEGEN: Generating message contract since the wrapper name (Delete_Result) of message Delete_Result does not match the default value (Delete)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/itemcategories:Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AX_CRT_Mage_Connector.Navision_ItemCategory_Service.Delete_Result Delete(AX_CRT_Mage_Connector.Navision_ItemCategory_Service.Delete request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemcategories")]
    public partial class ItemCategories : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string codeField;
        
        private string descriptionField;
        
        private string def_Gen_Prod_Posting_GroupField;
        
        private string def_Inventory_Posting_GroupField;
        
        private string def_VAT_Prod_Posting_GroupField;
        
        private Def_Costing_Method def_Costing_MethodField;
        
        private bool def_Costing_MethodFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Def_Gen_Prod_Posting_Group {
            get {
                return this.def_Gen_Prod_Posting_GroupField;
            }
            set {
                this.def_Gen_Prod_Posting_GroupField = value;
                this.RaisePropertyChanged("Def_Gen_Prod_Posting_Group");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Def_Inventory_Posting_Group {
            get {
                return this.def_Inventory_Posting_GroupField;
            }
            set {
                this.def_Inventory_Posting_GroupField = value;
                this.RaisePropertyChanged("Def_Inventory_Posting_Group");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Def_VAT_Prod_Posting_Group {
            get {
                return this.def_VAT_Prod_Posting_GroupField;
            }
            set {
                this.def_VAT_Prod_Posting_GroupField = value;
                this.RaisePropertyChanged("Def_VAT_Prod_Posting_Group");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public Def_Costing_Method Def_Costing_Method {
            get {
                return this.def_Costing_MethodField;
            }
            set {
                this.def_Costing_MethodField = value;
                this.RaisePropertyChanged("Def_Costing_Method");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Def_Costing_MethodSpecified {
            get {
                return this.def_Costing_MethodFieldSpecified;
            }
            set {
                this.def_Costing_MethodFieldSpecified = value;
                this.RaisePropertyChanged("Def_Costing_MethodSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemcategories")]
    public enum Def_Costing_Method {
        
        /// <remarks/>
        FIFO,
        
        /// <remarks/>
        LIFO,
        
        /// <remarks/>
        Specific,
        
        /// <remarks/>
        Average,
        
        /// <remarks/>
        Standard,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemcategories")]
    public partial class ItemCategories_Filter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ItemCategories_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ItemCategories_Fields Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
                this.RaisePropertyChanged("Field");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
                this.RaisePropertyChanged("Criteria");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemcategories")]
    public enum ItemCategories_Fields {
        
        /// <remarks/>
        Code,
        
        /// <remarks/>
        Description,
        
        /// <remarks/>
        Def_Gen_Prod_Posting_Group,
        
        /// <remarks/>
        Def_Inventory_Posting_Group,
        
        /// <remarks/>
        Def_VAT_Prod_Posting_Group,
        
        /// <remarks/>
        Def_Costing_Method,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read", WrapperNamespace="urn:microsoft-dynamics-schemas/page/itemcategories", IsWrapped=true)]
    public partial class Read {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemcategories", Order=0)]
        public string Code;
        
        public Read() {
        }
        
        public Read(string Code) {
            this.Code = Code;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/itemcategories", IsWrapped=true)]
    public partial class Read_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemcategories", Order=0)]
        public AX_CRT_Mage_Connector.Navision_ItemCategory_Service.ItemCategories ItemCategories;
        
        public Read_Result() {
        }
        
        public Read_Result(AX_CRT_Mage_Connector.Navision_ItemCategory_Service.ItemCategories ItemCategories) {
            this.ItemCategories = ItemCategories;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId", WrapperNamespace="urn:microsoft-dynamics-schemas/page/itemcategories", IsWrapped=true)]
    public partial class ReadByRecId {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemcategories", Order=0)]
        public string recId;
        
        public ReadByRecId() {
        }
        
        public ReadByRecId(string recId) {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/itemcategories", IsWrapped=true)]
    public partial class ReadByRecId_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemcategories", Order=0)]
        public AX_CRT_Mage_Connector.Navision_ItemCategory_Service.ItemCategories ItemCategories;
        
        public ReadByRecId_Result() {
        }
        
        public ReadByRecId_Result(AX_CRT_Mage_Connector.Navision_ItemCategory_Service.ItemCategories ItemCategories) {
            this.ItemCategories = ItemCategories;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/itemcategories", IsWrapped=true)]
    public partial class ReadMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemcategories", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("filter")]
        public AX_CRT_Mage_Connector.Navision_ItemCategory_Service.ItemCategories_Filter[] filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemcategories", Order=1)]
        public string bookmarkKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemcategories", Order=2)]
        public int setSize;
        
        public ReadMultiple() {
        }
        
        public ReadMultiple(AX_CRT_Mage_Connector.Navision_ItemCategory_Service.ItemCategories_Filter[] filter, string bookmarkKey, int setSize) {
            this.filter = filter;
            this.bookmarkKey = bookmarkKey;
            this.setSize = setSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/itemcategories", IsWrapped=true)]
    public partial class ReadMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadMultiple_Result", Namespace="urn:microsoft-dynamics-schemas/page/itemcategories", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public AX_CRT_Mage_Connector.Navision_ItemCategory_Service.ItemCategories[] ReadMultiple_Result1;
        
        public ReadMultiple_Result() {
        }
        
        public ReadMultiple_Result(AX_CRT_Mage_Connector.Navision_ItemCategory_Service.ItemCategories[] ReadMultiple_Result1) {
            this.ReadMultiple_Result1 = ReadMultiple_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated", WrapperNamespace="urn:microsoft-dynamics-schemas/page/itemcategories", IsWrapped=true)]
    public partial class IsUpdated {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemcategories", Order=0)]
        public string Key;
        
        public IsUpdated() {
        }
        
        public IsUpdated(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/itemcategories", IsWrapped=true)]
    public partial class IsUpdated_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUpdated_Result", Namespace="urn:microsoft-dynamics-schemas/page/itemcategories", Order=0)]
        public bool IsUpdated_Result1;
        
        public IsUpdated_Result() {
        }
        
        public IsUpdated_Result(bool IsUpdated_Result1) {
            this.IsUpdated_Result1 = IsUpdated_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey", WrapperNamespace="urn:microsoft-dynamics-schemas/page/itemcategories", IsWrapped=true)]
    public partial class GetRecIdFromKey {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemcategories", Order=0)]
        public string Key;
        
        public GetRecIdFromKey() {
        }
        
        public GetRecIdFromKey(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/itemcategories", IsWrapped=true)]
    public partial class GetRecIdFromKey_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecIdFromKey_Result", Namespace="urn:microsoft-dynamics-schemas/page/itemcategories", Order=0)]
        public string GetRecIdFromKey_Result1;
        
        public GetRecIdFromKey_Result() {
        }
        
        public GetRecIdFromKey_Result(string GetRecIdFromKey_Result1) {
            this.GetRecIdFromKey_Result1 = GetRecIdFromKey_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create", WrapperNamespace="urn:microsoft-dynamics-schemas/page/itemcategories", IsWrapped=true)]
    public partial class Create {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemcategories", Order=0)]
        public AX_CRT_Mage_Connector.Navision_ItemCategory_Service.ItemCategories ItemCategories;
        
        public Create() {
        }
        
        public Create(AX_CRT_Mage_Connector.Navision_ItemCategory_Service.ItemCategories ItemCategories) {
            this.ItemCategories = ItemCategories;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/itemcategories", IsWrapped=true)]
    public partial class Create_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemcategories", Order=0)]
        public AX_CRT_Mage_Connector.Navision_ItemCategory_Service.ItemCategories ItemCategories;
        
        public Create_Result() {
        }
        
        public Create_Result(AX_CRT_Mage_Connector.Navision_ItemCategory_Service.ItemCategories ItemCategories) {
            this.ItemCategories = ItemCategories;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/itemcategories", IsWrapped=true)]
    public partial class CreateMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemcategories", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public AX_CRT_Mage_Connector.Navision_ItemCategory_Service.ItemCategories[] ItemCategories_List;
        
        public CreateMultiple() {
        }
        
        public CreateMultiple(AX_CRT_Mage_Connector.Navision_ItemCategory_Service.ItemCategories[] ItemCategories_List) {
            this.ItemCategories_List = ItemCategories_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/itemcategories", IsWrapped=true)]
    public partial class CreateMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemcategories", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public AX_CRT_Mage_Connector.Navision_ItemCategory_Service.ItemCategories[] ItemCategories_List;
        
        public CreateMultiple_Result() {
        }
        
        public CreateMultiple_Result(AX_CRT_Mage_Connector.Navision_ItemCategory_Service.ItemCategories[] ItemCategories_List) {
            this.ItemCategories_List = ItemCategories_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update", WrapperNamespace="urn:microsoft-dynamics-schemas/page/itemcategories", IsWrapped=true)]
    public partial class Update {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemcategories", Order=0)]
        public AX_CRT_Mage_Connector.Navision_ItemCategory_Service.ItemCategories ItemCategories;
        
        public Update() {
        }
        
        public Update(AX_CRT_Mage_Connector.Navision_ItemCategory_Service.ItemCategories ItemCategories) {
            this.ItemCategories = ItemCategories;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/itemcategories", IsWrapped=true)]
    public partial class Update_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemcategories", Order=0)]
        public AX_CRT_Mage_Connector.Navision_ItemCategory_Service.ItemCategories ItemCategories;
        
        public Update_Result() {
        }
        
        public Update_Result(AX_CRT_Mage_Connector.Navision_ItemCategory_Service.ItemCategories ItemCategories) {
            this.ItemCategories = ItemCategories;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/itemcategories", IsWrapped=true)]
    public partial class UpdateMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemcategories", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public AX_CRT_Mage_Connector.Navision_ItemCategory_Service.ItemCategories[] ItemCategories_List;
        
        public UpdateMultiple() {
        }
        
        public UpdateMultiple(AX_CRT_Mage_Connector.Navision_ItemCategory_Service.ItemCategories[] ItemCategories_List) {
            this.ItemCategories_List = ItemCategories_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/itemcategories", IsWrapped=true)]
    public partial class UpdateMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemcategories", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public AX_CRT_Mage_Connector.Navision_ItemCategory_Service.ItemCategories[] ItemCategories_List;
        
        public UpdateMultiple_Result() {
        }
        
        public UpdateMultiple_Result(AX_CRT_Mage_Connector.Navision_ItemCategory_Service.ItemCategories[] ItemCategories_List) {
            this.ItemCategories_List = ItemCategories_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete", WrapperNamespace="urn:microsoft-dynamics-schemas/page/itemcategories", IsWrapped=true)]
    public partial class Delete {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemcategories", Order=0)]
        public string Key;
        
        public Delete() {
        }
        
        public Delete(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/itemcategories", IsWrapped=true)]
    public partial class Delete_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete_Result", Namespace="urn:microsoft-dynamics-schemas/page/itemcategories", Order=0)]
        public bool Delete_Result1;
        
        public Delete_Result() {
        }
        
        public Delete_Result(bool Delete_Result1) {
            this.Delete_Result1 = Delete_Result1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ItemCategories_PortChannel : AX_CRT_Mage_Connector.Navision_ItemCategory_Service.ItemCategories_Port, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ItemCategories_PortClient : System.ServiceModel.ClientBase<AX_CRT_Mage_Connector.Navision_ItemCategory_Service.ItemCategories_Port>, AX_CRT_Mage_Connector.Navision_ItemCategory_Service.ItemCategories_Port {
        
        public ItemCategories_PortClient() {
        }
        
        public ItemCategories_PortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ItemCategories_PortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ItemCategories_PortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ItemCategories_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AX_CRT_Mage_Connector.Navision_ItemCategory_Service.Read_Result AX_CRT_Mage_Connector.Navision_ItemCategory_Service.ItemCategories_Port.Read(AX_CRT_Mage_Connector.Navision_ItemCategory_Service.Read request) {
            return base.Channel.Read(request);
        }
        
        public AX_CRT_Mage_Connector.Navision_ItemCategory_Service.ItemCategories Read(string Code) {
            AX_CRT_Mage_Connector.Navision_ItemCategory_Service.Read inValue = new AX_CRT_Mage_Connector.Navision_ItemCategory_Service.Read();
            inValue.Code = Code;
            AX_CRT_Mage_Connector.Navision_ItemCategory_Service.Read_Result retVal = ((AX_CRT_Mage_Connector.Navision_ItemCategory_Service.ItemCategories_Port)(this)).Read(inValue);
            return retVal.ItemCategories;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AX_CRT_Mage_Connector.Navision_ItemCategory_Service.ReadByRecId_Result AX_CRT_Mage_Connector.Navision_ItemCategory_Service.ItemCategories_Port.ReadByRecId(AX_CRT_Mage_Connector.Navision_ItemCategory_Service.ReadByRecId request) {
            return base.Channel.ReadByRecId(request);
        }
        
        public AX_CRT_Mage_Connector.Navision_ItemCategory_Service.ItemCategories ReadByRecId(string recId) {
            AX_CRT_Mage_Connector.Navision_ItemCategory_Service.ReadByRecId inValue = new AX_CRT_Mage_Connector.Navision_ItemCategory_Service.ReadByRecId();
            inValue.recId = recId;
            AX_CRT_Mage_Connector.Navision_ItemCategory_Service.ReadByRecId_Result retVal = ((AX_CRT_Mage_Connector.Navision_ItemCategory_Service.ItemCategories_Port)(this)).ReadByRecId(inValue);
            return retVal.ItemCategories;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AX_CRT_Mage_Connector.Navision_ItemCategory_Service.ReadMultiple_Result AX_CRT_Mage_Connector.Navision_ItemCategory_Service.ItemCategories_Port.ReadMultiple(AX_CRT_Mage_Connector.Navision_ItemCategory_Service.ReadMultiple request) {
            return base.Channel.ReadMultiple(request);
        }
        
        public AX_CRT_Mage_Connector.Navision_ItemCategory_Service.ItemCategories[] ReadMultiple(AX_CRT_Mage_Connector.Navision_ItemCategory_Service.ItemCategories_Filter[] filter, string bookmarkKey, int setSize) {
            AX_CRT_Mage_Connector.Navision_ItemCategory_Service.ReadMultiple inValue = new AX_CRT_Mage_Connector.Navision_ItemCategory_Service.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            AX_CRT_Mage_Connector.Navision_ItemCategory_Service.ReadMultiple_Result retVal = ((AX_CRT_Mage_Connector.Navision_ItemCategory_Service.ItemCategories_Port)(this)).ReadMultiple(inValue);
            return retVal.ReadMultiple_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AX_CRT_Mage_Connector.Navision_ItemCategory_Service.IsUpdated_Result AX_CRT_Mage_Connector.Navision_ItemCategory_Service.ItemCategories_Port.IsUpdated(AX_CRT_Mage_Connector.Navision_ItemCategory_Service.IsUpdated request) {
            return base.Channel.IsUpdated(request);
        }
        
        public bool IsUpdated(string Key) {
            AX_CRT_Mage_Connector.Navision_ItemCategory_Service.IsUpdated inValue = new AX_CRT_Mage_Connector.Navision_ItemCategory_Service.IsUpdated();
            inValue.Key = Key;
            AX_CRT_Mage_Connector.Navision_ItemCategory_Service.IsUpdated_Result retVal = ((AX_CRT_Mage_Connector.Navision_ItemCategory_Service.ItemCategories_Port)(this)).IsUpdated(inValue);
            return retVal.IsUpdated_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AX_CRT_Mage_Connector.Navision_ItemCategory_Service.GetRecIdFromKey_Result AX_CRT_Mage_Connector.Navision_ItemCategory_Service.ItemCategories_Port.GetRecIdFromKey(AX_CRT_Mage_Connector.Navision_ItemCategory_Service.GetRecIdFromKey request) {
            return base.Channel.GetRecIdFromKey(request);
        }
        
        public string GetRecIdFromKey(string Key) {
            AX_CRT_Mage_Connector.Navision_ItemCategory_Service.GetRecIdFromKey inValue = new AX_CRT_Mage_Connector.Navision_ItemCategory_Service.GetRecIdFromKey();
            inValue.Key = Key;
            AX_CRT_Mage_Connector.Navision_ItemCategory_Service.GetRecIdFromKey_Result retVal = ((AX_CRT_Mage_Connector.Navision_ItemCategory_Service.ItemCategories_Port)(this)).GetRecIdFromKey(inValue);
            return retVal.GetRecIdFromKey_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AX_CRT_Mage_Connector.Navision_ItemCategory_Service.Create_Result AX_CRT_Mage_Connector.Navision_ItemCategory_Service.ItemCategories_Port.Create(AX_CRT_Mage_Connector.Navision_ItemCategory_Service.Create request) {
            return base.Channel.Create(request);
        }
        
        public void Create(ref AX_CRT_Mage_Connector.Navision_ItemCategory_Service.ItemCategories ItemCategories) {
            AX_CRT_Mage_Connector.Navision_ItemCategory_Service.Create inValue = new AX_CRT_Mage_Connector.Navision_ItemCategory_Service.Create();
            inValue.ItemCategories = ItemCategories;
            AX_CRT_Mage_Connector.Navision_ItemCategory_Service.Create_Result retVal = ((AX_CRT_Mage_Connector.Navision_ItemCategory_Service.ItemCategories_Port)(this)).Create(inValue);
            ItemCategories = retVal.ItemCategories;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AX_CRT_Mage_Connector.Navision_ItemCategory_Service.CreateMultiple_Result AX_CRT_Mage_Connector.Navision_ItemCategory_Service.ItemCategories_Port.CreateMultiple(AX_CRT_Mage_Connector.Navision_ItemCategory_Service.CreateMultiple request) {
            return base.Channel.CreateMultiple(request);
        }
        
        public void CreateMultiple(ref AX_CRT_Mage_Connector.Navision_ItemCategory_Service.ItemCategories[] ItemCategories_List) {
            AX_CRT_Mage_Connector.Navision_ItemCategory_Service.CreateMultiple inValue = new AX_CRT_Mage_Connector.Navision_ItemCategory_Service.CreateMultiple();
            inValue.ItemCategories_List = ItemCategories_List;
            AX_CRT_Mage_Connector.Navision_ItemCategory_Service.CreateMultiple_Result retVal = ((AX_CRT_Mage_Connector.Navision_ItemCategory_Service.ItemCategories_Port)(this)).CreateMultiple(inValue);
            ItemCategories_List = retVal.ItemCategories_List;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AX_CRT_Mage_Connector.Navision_ItemCategory_Service.Update_Result AX_CRT_Mage_Connector.Navision_ItemCategory_Service.ItemCategories_Port.Update(AX_CRT_Mage_Connector.Navision_ItemCategory_Service.Update request) {
            return base.Channel.Update(request);
        }
        
        public void Update(ref AX_CRT_Mage_Connector.Navision_ItemCategory_Service.ItemCategories ItemCategories) {
            AX_CRT_Mage_Connector.Navision_ItemCategory_Service.Update inValue = new AX_CRT_Mage_Connector.Navision_ItemCategory_Service.Update();
            inValue.ItemCategories = ItemCategories;
            AX_CRT_Mage_Connector.Navision_ItemCategory_Service.Update_Result retVal = ((AX_CRT_Mage_Connector.Navision_ItemCategory_Service.ItemCategories_Port)(this)).Update(inValue);
            ItemCategories = retVal.ItemCategories;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AX_CRT_Mage_Connector.Navision_ItemCategory_Service.UpdateMultiple_Result AX_CRT_Mage_Connector.Navision_ItemCategory_Service.ItemCategories_Port.UpdateMultiple(AX_CRT_Mage_Connector.Navision_ItemCategory_Service.UpdateMultiple request) {
            return base.Channel.UpdateMultiple(request);
        }
        
        public void UpdateMultiple(ref AX_CRT_Mage_Connector.Navision_ItemCategory_Service.ItemCategories[] ItemCategories_List) {
            AX_CRT_Mage_Connector.Navision_ItemCategory_Service.UpdateMultiple inValue = new AX_CRT_Mage_Connector.Navision_ItemCategory_Service.UpdateMultiple();
            inValue.ItemCategories_List = ItemCategories_List;
            AX_CRT_Mage_Connector.Navision_ItemCategory_Service.UpdateMultiple_Result retVal = ((AX_CRT_Mage_Connector.Navision_ItemCategory_Service.ItemCategories_Port)(this)).UpdateMultiple(inValue);
            ItemCategories_List = retVal.ItemCategories_List;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AX_CRT_Mage_Connector.Navision_ItemCategory_Service.Delete_Result AX_CRT_Mage_Connector.Navision_ItemCategory_Service.ItemCategories_Port.Delete(AX_CRT_Mage_Connector.Navision_ItemCategory_Service.Delete request) {
            return base.Channel.Delete(request);
        }
        
        public bool Delete(string Key) {
            AX_CRT_Mage_Connector.Navision_ItemCategory_Service.Delete inValue = new AX_CRT_Mage_Connector.Navision_ItemCategory_Service.Delete();
            inValue.Key = Key;
            AX_CRT_Mage_Connector.Navision_ItemCategory_Service.Delete_Result retVal = ((AX_CRT_Mage_Connector.Navision_ItemCategory_Service.ItemCategories_Port)(this)).Delete(inValue);
            return retVal.Delete_Result1;
        }
    }
}
